### PR TITLE
fixes #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure

### LINKED ISSUE #3349: Can not create custom procedure with void return type using apoc.custom.declareProcedure
## Guidelines

It is not able to create a custom procedure using  apoc.custom.declareProcedure for void return type . 

dbms.setConfigValue() returns void and custom procedure can not be created . 

```
CALL apoc.custom.declareProcedure(
  'setrole(ssorole::STRING) :: (row::MAP)',
  
  'CALL {CALL dbms.listConfig() YIELD name, value WHERE name CONTAINS "dbms.security.oidc.keycloak.authorization.group_to_role_mapping" RETURN value} 
  WITH value
  CALL dbms.setConfigValue("dbms.security.oidc.keycloak.authorization.group_to_role_mapping",value+$ssorole);'
  
);
```
Throws ==> Failed to invoke procedure `apoc.custom.declareProcedure`: Caused by: java.lang.NullPointerException

## Expected Behavior (Mandatory)

It should create a custom procedure 

## Actual Behavior (Mandatory)

Throws ==> Failed to invoke procedure `apoc.custom.declareProcedure`: Caused by: java.lang.NullPointerException
## How to Reproduce the Problem

Run the above code 

Currently used versions

### Versions

  - OS:
  - Neo4j:4.4.11
  - Neo4j-Apoc:4.4.11

### PR DESCRIPTION
**Pull request by conker84**
Fixes #3349

Extended Cypher Procedures in order to support `DBMS` and `SCHEMA` procedures.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added the new modes
  - Added Test

### CODE REVIEW

File: full/src/test/java/apoc/custom/CypherProceduresTest.java [hunk 1]
```diff
@@ -839,6 +847,23 @@ public void testIssue2032() {
         assertProcedureFails(String.format(SIGNATURE_SYNTAX_ERROR, procedureSignature), 
                 "call apoc.custom.declareProcedure('" + procedureSignature + "','RETURN $first + $s AS answer')");
     }
+
+    @Test
+    public void testIssue3349() {
+        String procedure = "CALL apoc.custom.declareProcedure(\n" +
```
Comment (gem-neo4j) [inline full/src/test/java/apoc/custom/CypherProceduresTest.java:853]: The issue asks for a void return type from what I can tell, this looks like it is testing not having any parameters to pass in, can a test be added for testing a void return? Or will that be separate?

Comment (conker84) [reply full/src/test/java/apoc/custom/CypherProceduresTest.java:853]: @gem-neo4j thanks for the question, the issue has an example with the following signature:
`setrole(ssorole::STRING) :: (row::MAP)`, that triggers an error, then the user said that he also tested with `VOID` return type. So as the issue is not related to the return type but to the fact (as discussed in the trello card) that was not meant to manage `DBMS` and `SCHEMA` query types, I used an example as much similar as possible to the one shared in the GH issue (https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3349).

Btw if you want I can add a test also with the return type.

Do you also want a test with a custom procedure with parameters? With `VOID` or another return type?

Comment (gem-neo4j) [reply full/src/test/java/apoc/custom/CypherProceduresTest.java:853]: It would be nice to have, considering the title of this fix specifies it is for void return type :)

Comment (conker84) [reply full/src/test/java/apoc/custom/CypherProceduresTest.java:853]: @gem-neo4j done!

**Review by gem-neo4j — APPROVED** [review]

**Comment by conker84** [comment]
I merged it because the CI was red for this test `TriggerNewProceduresTest#testTriggerPause` which I suppose it's flaky
