### PR TITLE
Fixes #1749: In version 4 of the database there is property dbms.directories.neo4j_home without unsupported. prefix

### LINKED ISSUE #1749: In version 4 of the database there is property "dbms.directories.neo4j_home" without "unsupported." prefix
In FileUtils.getLogDirectory() the home dir of the neo4j installation is retrieved via the database configuration properties. It uses the 'home directory' as a fail save if the dbms.directories.logs value is empty. 

It uses the property key "unsupported.dbms.directories.neo4j_home", but in Neo4j version 4 this is replaced by "dbms.directories.neo4j_home".

something like this would work
```    
public static File getLogDirectory(Log log) {
        String neo4jHome = apocConfig().getString("unsupported.dbms.directories.neo4j_home", "");
        if (neo4jHome == null || neo4jHome.isEmpty()) {
            neo4jHome = apocConfig().getString("dbms.directories.neo4j_home", "");
        }
        String logDir = apocConfig().getString("dbms.directories.logs", "");

        File logs = logDir.isEmpty() ? new File(neo4jHome, "logs") : new File(logDir);
        if (logs.exists() && logs.canRead() && logs.isDirectory()) {
            return logs;
        }

        return null;
    }
```

### PR DESCRIPTION
**Pull request by vga91**
Fixes #1749

- Added `Neo4jLogStreamTest`

### CODE REVIEW

File: core/src/test/java/apoc/log/Neo4jLogStreamTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+        DatabaseManagementService dbManagementService = new TestDatabaseManagementServiceBuilder(
+                Paths.get("target").toAbsolutePath()).build();
+        apocConfig().setProperty("dbms.directories.logs", "");
+        db = dbManagementService.database(GraphDatabaseSettings.DEFAULT_DATABASE_NAME);
+        TestUtil.registerProcedure(db, Neo4jLogStream.class);
+    }
+    
+    @Test
+    public void testLogStream() {
+        testResult(db, "CALL apoc.log.stream('debug.log')", res -> {
```
Comment (fbiville) [inline core/src/test/java/apoc/log/Neo4jLogStreamTest.java:34]: Would the test fail without the change in `FileUtils#getLogDirectory`?
Or is the intention to just improve test coverage regardless?

**Review by fbiville — APPROVED** [review]

File: core/src/test/java/apoc/log/Neo4jLogStreamTest.java (hunk 1 above)
Comment (vga91) [reply core/src/test/java/apoc/log/Neo4jLogStreamTest.java:34]: Yes, it fails without the change
