### PR TITLE
fixes #789 - APOC Intersection JSON Number parsing issue

### LINKED ISSUE #789: APOC Intersection issue
Case2 below should work without explicitly casting between Integers or Longs.  Case4 shows a current work-around for this.

/* case1: this works */
WITH [1,2] as set1, [2,3] as set2
WITH apoc.coll.intersection(set1, set2) as intersection
RETURN intersection

/* case2: this doesn't work */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
WITH apoc.coll.intersection(set1.numbers, set2) as intersection
RETURN intersection

/* case3: this works */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
RETURN filter(number IN set1.numbers WHERE number IN set2) as intersection

/* case4: works - work around for case2 */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
WITH apoc.coll.intersection([x in set1.numbers | tointeger(x)], set2) as intersection
RETURN intersection

### PR DESCRIPTION
**Pull request by AngeloBusato**

### CODE REVIEW

File: src/test/java/apoc/spatial/GeocodeTest.java [hunk 1]
```diff
@@ -151,7 +151,7 @@ private void testGeocodeAddress(Map map, String provider) {
                 }
                 testCallCount(db, "CALL apoc.spatial.geocode({url},0)",
                         map("url", map.get("address").toString()),
-                        (int) ((Map) map.get("count")).get(provider));
+                        Integer.parseInt(((Map) map.get("count")).get(provider).toString()));
```
Comment (jexp) [inline src/test/java/apoc/spatial/GeocodeTest.java]: use Number.intValue()

File: src/test/java/apoc/schema/SchemasTest.java [hunk 2]
```diff
@@ -268,7 +268,7 @@ public void testIndexes() {
             assertEquals("NO FAILURE", r.get("failure"));
             assertEquals(new Double(100), r.get("populationProgress"));
             assertEquals(new Double(1), r.get("valuesSelectivity"));
-            assertEquals("Index( GENERAL, bar )", r.get("userDescription"));
+            assertEquals("Index( GENERAL, :Foo(bar) )", r.get("userDescription"));
```
Comment (jexp) [inline src/test/java/apoc/schema/SchemasTest.java]: this seems to have changed between Neo4j versions.

File: src/main/java/apoc/util/JsonUtil.java [hunk 3]
```diff
@@ -73,10 +77,13 @@ public void close() throws IOException {
     public static <T> T parse(String json, String path, Class<T> type) {
         if (json==null || json.isEmpty()) return null;
         try {
-            if (path == null || path.isEmpty()) return OBJECT_MAPPER.readValue(json, type);
-            return JsonPath.parse(json,JSON_PATH_CONFIG).read(path,type);
+            if (path == null || path.isEmpty()) {
+                return OBJECT_MAPPER.readValue(json, type);
+            }
+            String stringValue = OBJECT_MAPPER.writeValueAsString(JsonPath.parse(json,JSON_PATH_CONFIG).read(path, type));
```
Comment (jexp) [inline src/main/java/apoc/util/JsonUtil.java]: Can we please not do this, and find a way to avoid creating new huge string objects in memory?

File: src/test/java/apoc/spatial/GeocodeTest.java (hunk 1 above)
Comment (conker84) [reply src/test/java/apoc/spatial/GeocodeTest.java]: We restored the previous version the value of `((Map) map.get("count")).get(provider))` is aready and integer.

File: src/main/java/apoc/util/JsonUtil.java (hunk 3 above)
Comment (conker84) [reply src/main/java/apoc/util/JsonUtil.java]: Done we now inject Jackson into JsonPath

Comment (jexp) [reply src/main/java/apoc/util/JsonUtil.java]: Great!

**Comment by jexp** [comment]
@conker84 something interesting about the "intersection" in general is that there might be lists of mixed numbers. like doubles and longs and then folks might expect cypher semantics of `1.0 == 1`.

But we should cover that in a separate issue I think.
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/972

**Comment by jexp** [comment]
Thanks a lot.
