### PR TITLE
fixes #1568: apoc.custom.list displays procedure name but execution errors out with

### LINKED ISSUE #1568: apoc.custom.list displays procedure name but execution errors out with `There is no procedure with the name`
## Expected Behavior
After deploying a new APOC custom procedure I expect it to be found and executed.

## Actual Behavior
For full stract trace please see below:
```
2020-06-16 13:32:24.502+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: There is no procedure with the name `custom.copy_course` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed., reference aeb0d3fa-4e8a-4491-8556-a8573aa8477d. There is no procedure with the name `custom.copy_course` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
org.neo4j.graphdb.QueryExecutionException: There is no procedure with the name `custom.copy_course` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
at apoc.custom.CypherProcedures$CustomStatementRegistry$2.apply(CypherProcedures.java:231)
at org.neo4j.kernel.impl.proc.ProcedureRegistry.callProcedure(ProcedureRegistry.java:219)
at org.neo4j.kernel.impl.proc.Procedures.callProcedure(Procedures.java:290)
at org.neo4j.kernel.impl.newapi.AllStoreHolder.callProcedure(AllStoreHolder.java:1098)
at org.neo4j.kernel.impl.newapi.AllStoreHolder.procedureCallWrite(AllStoreHolder.java:884)
at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$$anonfun$4.apply(CallSupport.scala:73)
at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$$anonfun$4.apply(CallSupport.scala:73)
at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callProcedure(CallSupport.scala:167)
at org.neo4j.cypher.internal.runtime.interpreted.CallSupport$.callReadWriteProcedure(CallSupport.scala:74)
at org.neo4j.cypher.internal.runtime.interpreted.TransactionBoundQueryContext.callReadWriteProcedure(TransactionBoundQueryContext.scala:977)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:169)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext$$anonfun$callReadWriteProcedure$1.apply(ExceptionTranslatingQueryContext.scala:169)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateException(ExceptionTranslationSupport.scala:33)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateException(ExceptionTranslatingQueryContext.scala:42)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslationSupport$class.translateIterator(ExceptionTranslationSupport.scala:47)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.translateIterator(ExceptionTranslatingQueryContext.scala:42)
at org.neo4j.cypher.internal.compatibility.v3_5.ExceptionTranslatingQueryContext.callReadWriteProcedure(ExceptionTranslatingQueryContext.scala:169)
at org.neo4j.cypher.internal.runtime.interpreted.DelegatingQueryContext.callReadWriteProcedure(DelegatingQueryContext.scala:253)
at org.neo4j.cypher.internal.runtime.EagerReadWriteCallMode.callProcedure(ProcedureCallMode.scala:66)
at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe.org$neo4j$cypher$internal$runtime$interpreted$pipes$ProcedureCallPipe$$call(ProcedureCallPipe.scala:90)
at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$e6882d5096c8b8441ac36d3c0cc459e$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:73)
at org.neo4j.cypher.internal.runtime.interpreted.pipes.ProcedureCallPipe$$anon$$$$e6882d5096c8b8441ac36d3c0cc459e$$$$ateResultsByAppending$1.apply(ProcedureCallPipe.scala:71)
at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
at org.neo4j.cypher.internal.runtime.RuntimeJavaValueConverter$feedQueryResultRecordIteratorToVisitable.accept(RuntimeJavaValueConverter.scala:63)
at org.neo4j.cypher.internal.compatibility.v3_5.runtime.PipeExecutionResult.accept(PipeExecutionResult.scala:74)
at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.materializeResult(StandardInternalExecutionResult.scala:77)
at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.initiate(StandardInternalExecutionResult.scala:59)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$initiate$1.apply$mcV$sp(ClosingExecutionResult.scala:65)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$initiate$1.apply(ClosingExecutionResult.scala:65)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$initiate$1.apply(ClosingExecutionResult.scala:65)
at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.org$neo4j$cypher$internal$compatibility$ClosingExecutionResult$$safely(ClosingExecutionResult.scala:167)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.initiate(ClosingExecutionResult.scala:65)
at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$.wrapAndInitiate(ClosingExecutionResult.scala:214)
at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:216)
at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$3.apply(CypherCurrentCompiler.scala:190)
at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery.execute(CypherCurrentCompiler.scala:223)
at org.neo4j.cypher.internal.ExecutionEngine.execute(ExecutionEngine.scala:116)
at org.neo4j.cypher.internal.javacompat.ExecutionEngine.executeQuery(ExecutionEngine.java:85)
at org.neo4j.bolt.v1.runtime.TransactionStateMachineV1SPI$BoltResultHandleV1.start(TransactionStateMachineV1SPI.java:189)
at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.startExecution(TransactionStateMachine.java:506)
at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$2.run(TransactionStateMachine.java:385)
at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:110)
at org.neo4j.bolt.v1.runtime.TransactionStateMachine.run(TransactionStateMachine.java:98)
at org.neo4j.bolt.v3.runtime.TransactionReadyState.processRunMessage(TransactionReadyState.java:82)
at org.neo4j.bolt.v3.runtime.TransactionReadyState.processUnsafe(TransactionReadyState.java:49)
at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.lambda$enqueue$0(MetricsReportingBoltConnection.java:68)
at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
at org.neo4j.bolt.runtime.MetricsReportingBoltConnection.processNextBatch(MetricsReportingBoltConnection.java:86)
at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

#### Procedure creation
```
CALL apoc.custom.asProcedure(
"copy_course",
"// Clone individual Course node and set the version
CALL apoc.log.info('Entry in copyCourse from courseId %d', [$courseId])
MATCH (course:Course)
WHERE ID(course) = $courseId
SET course.clonePairingId=course.externalId
WITH course as course
CALL apoc.refactor.cloneNodes([course], false, $skipProperties) YIELD output as clonedCourse
SET clonedCourse.version=$newCourseVersion
WITH course as course, clonedCourse as clonedCourse
// Create a COPIED relationship back to the original course
CREATE (clonedCourse)-[:COPIED {copyType:$copyType}]->(course)
WITH course as course, clonedCourse as clonedCourse
// Build Course Subgraph (excluding blacklisted nodes)
OPTIONAL MATCH path = (course)-[r1]-(level1:CourseContext)
WHERE TYPE(r1) <> 'COPIED'
AND NONE(label IN LABELS(level1) WHERE label IN $skipLabels)
WITH COLLECT(path) AS pathTotal, course as course, clonedCourse as clonedCourse
// Level 2 nodes
OPTIONAL MATCH path2 = (course)-[r1]-(level1:CourseContext)-[r2]-(level2:CourseContext)
WHERE TYPE(r1) <> 'COPIED' AND TYPE(r2) <> 'COPIED'
AND NONE(label IN LABELS(level1) WHERE label IN $skipLabels)
AND NONE(label IN LABELS(level2) WHERE label IN $skipLabels)
WITH pathTotal + COLLECT(path2) AS pathTotal2, course as course, clonedCourse as clonedCourse
// Level 3 nodes
OPTIONAL MATCH path3 = (course)-[r1]-(level1:CourseContext)-[r2]-(level2:CourseContext)-[r3]-(level3:CourseContext)
WHERE TYPE(r1) <> 'COPIED' AND TYPE(r2) <> 'COPIED' AND TYPE(r3) <> 'COPIED'
AND NONE(label IN LABELS(level1) WHERE label IN $skipLabels)
AND NONE(label IN LABELS(level2) WHERE label IN $skipLabels)
AND NONE(label IN LABELS(level3) WHERE label IN $skipLabels)
WITH pathTotal2 + COLLECT(path3) AS pathTotal3, course as course, clonedCourse as clonedCourse
// Clone the non-blacklisted Course Subgraph
CALL apoc.refactor.cloneSubgraphFromPaths(pathTotal3, {standinNodes:[[course, clonedCourse]], skipProperties:$skipProperties}) YIELD input, output, error
WITH DISTINCT clonedCourse as clonedCourse, course as course
// Create relationships from Course to CourseResource
MATCH (course)-[r:COURSE_AND_COURSE_RESOURCE]->(courseResource:CourseResource)
CREATE (clonedCourse)-[r2:COURSE_AND_COURSE_RESOURCE {createdBy:'COURSE_COPY', createdDate:timestamp()}]->(courseResource)
SET r2.order=r.order, r2.progenitorId=r.progenitorId
WITH DISTINCT course as course, clonedCourse as clonedCourse
CALL apoc.log.info('HERE! of copyCourse with source courseId %d.', [$courseId])
WITH DISTINCT course as course, clonedCourse as clonedCourse
// Create relationships from CourseResourceReferences to CourseResources
MATCH (course)-[]-(:CourseContext)-[]-(ref:CourseContext:CourseResourceReference)<-[r:COURSE_RESOURCE_AND_COURSE_RESOURCE_REFERENCE]-(courseResource:CourseResource)
WITH course as course, clonedCourse as clonedCourse, courseResource as courseResource, ref as ref, r as r
MATCH (clonedCourse)-[]-(:CourseContext)-[]-(ref2:CourseContext:CourseResourceReference) WHERE ref2.clonePairingId=ref.externalId
WITH DISTINCT course as course, clonedCourse as clonedCourse, courseResource as courseResource, ref as ref, ref2 as ref2, r as r
CREATE (courseResource)-[r2:COURSE_RESOURCE_AND_COURSE_RESOURCE_REFERENCE {createdBy:'COURSE_COPY', createdDate:timestamp()}]->(ref2)
SET r2.order=r.order, r2.progenitorId=r.progenitorId
WITH DISTINCT course as course, clonedCourse as clonedCourse
CALL apoc.log.info('HERE2! of copyCourse with source courseId %d.', [$courseId])
WITH DISTINCT course as course, clonedCourse as clonedCourse
// Create relationships from CourseResourceReferences to CourseResourceFormats
MATCH (course)-[]-(:CourseContext)-[]-(ref:CourseContext:CourseResourceReference)<-[r:COURSE_RESOURCE_FORMAT_AND_COURSE_RESOURCE_REFERENCE]-(crf:CourseResourceFormat)
WITH course as course, clonedCourse as clonedCourse, crf as crf, ref as ref, r as r
MATCH (clonedCourse)-[]-(:CourseContext)-[]-(ref2:CourseContext:CourseResourceReference) WHERE ref2.clonePairingId=ref.externalId
WITH DISTINCT course as course, clonedCourse as clonedCourse, crf as crf, ref as ref, ref2 as ref2, r as r
CREATE (crf)-[r2:COURSE_RESOURCE_FORMAT_AND_COURSE_RESOURCE_REFERENCE {createdBy:'COURSE_COPY', createdDate:timestamp()}]->(ref2)
SET r2.order=r.order, r2.progenitorId=r.progenitorId
WITH DISTINCT clonedCourse as clonedCourse
CALL apoc.log.info('Exit of copyCourse with source courseId %d.', [$courseId])
RETURN clonedCourse AS clonedCourse",
"write",
[['clonedCourse', 'NODE']],
[['courseId', 'LONG'], ['newCourseVersion', 'DOUBLE'], ['copyType', 'STRING'], ['skipProperties', 'LIST OF STRING'], ['skipLabels', 'LIST OF STRING']],
"Copies a given course by courseId including relationships and omitting properties as specified in skipProperties and labels as specified in skipLabels");
```

#### Procedure call
```
WITH
7631095 as courseId,
1.0 AS newCourseVersion,
'COURSE_COPY' AS copyType,
['guid', 'externalId', 'createdBy', 'createdDate', 'updatedBy', 'updatedDate'] AS skipProperties,
['Note', 'VersionCategory'] AS skipLabels
call custom.copy_course(courseId, newCourseVersion, copyType, skipProperties, skipLabels) YIELD clonedCourse
return clonedCourse;
```

#### Actual behavior
At first, execution if succeeds and then fails subsequent executions.

## Screenshots (where it's possibile)
Screenshot from neo4j browser 
neo4j_browser

### Versions

  - OS: Windows 2010
  - Neo4j: 3.5.18 (single instance)
  - Neo4j-Apoc: 3.5.0.12

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1568

The bug was related to the cancellation of a procedure/function that once done gets deleted every scheduled loop.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added test case
  - Fixed the bug

### CODE REVIEW

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java [hunk 1]
```diff
@@ -151,4 +146,38 @@ public void shouldRemoveFunctionOnOtherClusterMembers() throws InterruptedExcept
             throw e;
         }
     }
+
+    @Test
+    public void overrideCallStatementWithNewArguments() throws Exception {
```
Comment (fbiville) [inline src/test/java/apoc/custom/CypherProceduresClusterTest.java:151]: I don't see any `apoc.custom.list` call or equivalent in the tests, shouldn't there be some kind of assertions making sure a deleted procedure or function is not listed anymore?

File: src/test/java/apoc/custom/CypherProceduresTest.java [hunk 2]
```diff
@@ -29,7 +30,10 @@
 
     @Before
     public void setUp() throws Exception {
-        db = new TestGraphDatabaseFactory().newImpermanentDatabase();
+        db = new TestGraphDatabaseFactory()
+                .newImpermanentDatabaseBuilder()
+                .setConfig("apoc.custom.procedures.refresh", "100")
```
Comment (fbiville) [inline src/test/java/apoc/custom/CypherProceduresTest.java:35]: not needed in the cluster tests?

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java [hunk 3]
```diff
@@ -15,15 +15,10 @@
 import java.util.List;
 import java.util.Map;
 
-import static apoc.util.TestContainerUtil.cleanBuild;
-import static apoc.util.TestContainerUtil.executeGradleTasks;
-import static apoc.util.TestContainerUtil.testCall;
-import static apoc.util.TestContainerUtil.testCallInReadTransaction;
+import static apoc.util.TestContainerUtil.*;
```
Comment (fbiville) [inline src/test/java/apoc/custom/CypherProceduresClusterTest.java:18]: very personal opinion ^^ -> I prefer single-class imports (on the sole basis that they are grep-friendlier)

File: src/main/java/apoc/custom/CypherProcedures.java [hunk 4]
```diff
@@ -589,30 +655,31 @@ public void unavailable() {
...
-            return updateCustomData(getProperties(api),name, type,null);
+            return updateCustomData(api,name, type,null);
         }
 
-        private synchronized static Map<String, Object> updateCustomData(GraphProperties properties, String name, String type, Map<String, Object> value) {
+        private synchronized static Map<String, Object> updateCustomData(GraphDatabaseAPI api, String name, String type, Map<String, Object> value) {
             if (name == null || type==null) return null;
-            try (Transaction tx = properties.getGraphDatabase().beginTx()) {
+            GraphProperties properties = getProperties(api);
+            try (Transaction tx = api.beginTx()) {
```
Comment (fbiville) [inline src/main/java/apoc/custom/CypherProcedures.java:682]: what's the difference between this and the previous version?

**Review by fbiville — COMMENTED** [review]
I will do a thorougher review soon, but I already have a few questions

File: src/main/java/apoc/custom/CypherProcedures.java [hunk 5]
```diff
@@ -508,6 +543,9 @@ public CustomProcedureInfo(String type, String name, String description, String
         public static Group REFRESH_GROUP = Group.STORAGE_MAINTENANCE;
         private JobHandle restoreProceduresHandle;
 
+        private static final Set<ProcedureSignature> registeredProcedure = Collections.synchronizedSet(new HashSet<>());
```
[the remark this answers is not in the document]
Comment (conker84) [reply src/main/java/apoc/custom/CypherProcedures.java]: Done

File: src/main/java/apoc/custom/CypherProcedures.java [hunk 6]
```diff
@@ -508,6 +543,9 @@ public CustomProcedureInfo(String type, String name, String description, String
...
+        private static final Set<UserFunctionSignature> registeredUserFunction = Collections.synchronizedSet(new HashSet<>());
```
[the remark this answers is not in the document]
Comment (conker84) [reply src/main/java/apoc/custom/CypherProcedures.java]: Done

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java (hunk 1 above)
Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:151]: Oh I didn't add it in here because we have other tests to track that feature

File: src/test/java/apoc/custom/CypherProceduresTest.java (hunk 2 above)
Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresTest.java:35]: We already have it in there:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3575757f02a7e0adedd422d7c5a20d05edce4f9e/src/test/java/apoc/custom/CypherProceduresClusterTest.java#L37

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java (hunk 3 above)
Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:18]: I agree with you I just changed the notebook and forgot to change the Intellij properties, thanks for point this out!

File: src/main/java/apoc/custom/CypherProcedures.java (hunk 4 above)
Comment (conker84) [reply src/main/java/apoc/custom/CypherProcedures.java]: reverted was related to a change that I reverted

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java (hunk 1 above)
Comment (fbiville) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:156]: I see, but the initial issue is about discrepancies between `apoc.custom.list` and the actual runnable procedures/functions, isn't it?
When I first read the test, I could not make the connection between the initial problem and how the test makes sure it does not happen anymore.

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:156]: Yes that tricked also us but the `apoc.custom.list` worked properly because after the remove the user added the procedure again, the problem was the background job triggered by the scheduler that cancelled under-the-hood the procedure because the same was inside the `removed` field in the json stored into the graph properties.
Btw you comment made me think that we should get rid of the `removed` field just to avoid future confusions.
I updated the code base, please look at it and lemme know if you still need the test for `apoc.custom.list`

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java [hunk 7]
```diff
@@ -151,4 +151,38 @@ public void shouldRemoveFunctionOnOtherClusterMembers() throws InterruptedExcept
...
+        try {
+            Thread.sleep(1000);
+            Assert.fail("procedure not removed");
+        } catch (Exception e) {
+            assertTrue(e instanceof DatabaseException);
+        }
+        // creating a new one, this triggers the scheduler
+        cluster.getSession().run("call apoc.custom.asProcedure('answer','RETURN $input as answer','read',[['answer','number']],[['input','int','42']], 'Procedure that answer to the Ultimate Question of Life, the Universe, and Everything')");
+        // waiting that the scheduler has been triggered
+        Thread.sleep(1000);
```
Comment (fbiville) [inline src/test/java/apoc/custom/CypherProceduresClusterTest.java:176]: could you call `apoc.custom.list` until the procedure appears (or a timeout is reached) instead?

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:178]: done, I also added a test for the `apoc.custom.list`

Comment (fbiville) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:178]: hmmm, I might be missing something, but my thinking was we could replace `Thread.sleep(1000)`
with sth like (warning: not tested at all):
```java
boolean inList = false;
while (!inList) { // TBD: timeout, to avoid running an infinite loop in case of issues
       // TBD: result from `CALL apoc.custom.list()`
       inList = Iterators.asList(result)
                         .stream()
                         .map(row -> row.get("name"))
                         .filter(name -> "answer".equals(name))
                         .findAny()
                         .isPresent();
}
```

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:178]: Sorry can you elaborate why we should do that? The `Thread.sleep(1000);` is in there just to be sure that the scheduler has been executed and a cycle of `restoreProcedures` is completed, is not connected to the `apoc.custom.list`:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/692db025d13a0eb7b488e3485aa6223c4b315740/src/main/java/apoc/custom/CypherProcedures.java#L597

Comment (fbiville) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java:178]: It seems to me that `Thread.sleep(1000)` relies on a "magic value", based on the internal knowledge of the current procedure/function registration implementation. Is it guaranteed that waiting 1 second is always to be enough under any circumstance?

Taking a step back, I was thinking of the following invariants:

- a procedure/function is registered as soon as it is listed (with `apoc.custom.list` e.g.)
- a procedure/function is removed as soon as it is not listed (with `apoc.custom.list` e.g.)

Implementing the wait loop based on these seem a little more future-proof?

File: src/main/java/apoc/custom/CypherProcedures.java [hunk 8]
```diff
@@ -167,6 +204,37 @@ public void removeFunction(@Name("name") String name) {
         Procedures procedures;
         private final Log log;
 
+        public ProcedureSignature createProcedureSignature(String name, Map<String, Object> procedureMetadata) {
```
Comment (fbiville) [inline src/main/java/apoc/custom/CypherProcedures.java:207]: Intellij tells me this method is unused

File: src/main/java/apoc/custom/CypherProcedures.java [hunk 9]
```diff
@@ -167,6 +204,37 @@ public void removeFunction(@Name("name") String name) {
...
+                return Signatures.createProcedureSignature(qualifiedName(name),
+                        inputSignatures((List<List<String>>) procedureMetadata.get("inputs")),
+                        outputSignatures((List<List<String>>) procedureMetadata.get("outputs")),
+                        mode((String) procedureMetadata.get("mode")), false, null, new String[0],
+                        (String) procedureMetadata.get("description"), null, false, true, false
+                );
+            }
+        }
+
+        public UserFunctionSignature createUserFunctionSignature(String name, Map<String, Object> functionMetadata) {
```
Comment (fbiville) [inline src/main/java/apoc/custom/CypherProcedures.java:223]: Intellij tells me this method is unused

File: src/main/java/apoc/custom/CypherProcedures.java (hunk 8 above)
Comment (conker84) [reply src/main/java/apoc/custom/CypherProcedures.java]: removed

File: src/main/java/apoc/custom/CypherProcedures.java (hunk 9 above)
Comment (conker84) [reply src/main/java/apoc/custom/CypherProcedures.java]: removed

File: src/test/java/apoc/custom/CypherProceduresClusterTest.java (hunk 7 above)
Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java]: Ok I did it can you please check?

Comment (fbiville) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java]: My previous comment was an attempt to explain why I suggested the (incomplete) code snippet above :)

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresClusterTest.java]: I used `assertEventually` that should basically do the same, do you prefer something else?

File: core/src/test/resources/csv-inputs/array.csv [hunk 10]
```diff
@@ -0,0 +1,2 @@
+:ID|name:STRING[]
```
Comment (fbiville) [inline core/src/test/resources/csv-inputs/array.csv:1]: there are many CSVs now, is that intentional?

Comment (conker84) [reply core/src/test/resources/csv-inputs/array.csv]: Something happened when I switched from branch `4.1` where I was working on before your last comments, I removed the files. Thank you!

**Review by fbiville — APPROVED** [review]

**Comment by fbiville** [comment]
I'm not sure what the CI failures are about, they do seem related to your changes at first glance, @conker84.
What do you think?

**Comment by conker84** [comment]
@fbiville let me investigate il be back ASAP

**Comment by conker84** [comment]
@fbiville @JMHReif I updated the PR with this two lines that will fix the broken test:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/e8f8fe3879564f58a681f68f1817c6481a68b73e/src/main/java/apoc/custom/CypherProcedures.java#L639-L640
