### PR TITLE
[pb3CtuNX] Adds convert.paths.toTree to deprecate old convert.toTree

### LINKED ISSUE #3996: apoc.convert.toTree() returns wrong result if there is a cycle from root of the path
In the path responses below, there is a cycle starting from node(10), which is the root of the path while preparing the tree. This [line](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/82217ad5c89bafc2f5e61df897d317b29ee0dfa6/core/src/main/java/apoc/convert/Json.java#L219C24-L219C51)  blindly replaces the map, leading to the issue where few nodes are getting missed in the tree response.

```
(10)-[FLOW,19]->(4)-[FLOW,2]->(12)-[FLOW,17]->(6)-[FLOW,7]->(11)-[FLOW,16]->(8), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,3]->(9), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,3]->(9)-[FLOW,18]->(7), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,6]->(15), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,6]->(15)-[FLOW,11]->(3), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,7]->(11), 

(10)-[FLOW,19]->(4)-[FLOW,8]->(17)-[FLOW,12]->(6)-[FLOW,7]->(11)-[FLOW,16]->(8), 

(10)-[FLOW,19]->(4)-[FLOW,9]->(13), 

(10)-[FLOW,19]->(4)-[FLOW,9]->(13)-[FLOW,14]->(7), 

(10)-[FLOW,19]->(4)-[FLOW,9]->(13)-[FLOW,14]->(7)-[FLOW,4]->(10),  // cycle

(10)-[FLOW,19]->(4)-[FLOW,9]->(13)-[FLOW,14]->(7)-[FLOW,10]->(16), 

(10)-[FLOW,19]->(4)-[FLOW,9]->(13)-[FLOW,14]->(7)-[FLOW,10]->(16)-[FLOW,15]->(3), 

(16)-[FLOW,15]->(3), 

(16)-[FLOW,15]->(3)-[FLOW,5]->(14), 

(16)-[FLOW,15]->(3)-[FLOW,5]->(14)-[FLOW,13]->(5)]
```

### PR DESCRIPTION
**Pull request by ncordon**
## What

Adds a new method `convert.paths.toTree` that deprecates `convert.toTree`.

Closes #3996, #3997

## Why

There were several problems with the old method. For paths:

```
v1 -> v2 -> v3
v2 -> v2 //self-loop
```

it was outputting:

```
v1 -> v2 -> v2
v2 -> v2
```

instead of:

```
v1 -> v2 -> v2
         -> v3
```

This PR adds a new method that:
* Fixes the behaviour for cyclic paths.
* Fixes the behaviour for bidirectional paths.
* Fixes the properties filter for both of the method when the nodes have several labels.

### CODE REVIEW

File: core/src/main/java/apoc/convert/Json.java [hunk 1]
```diff
@@ -231,6 +231,73 @@ public Stream<MapResult> toTree(
                 .map(MapResult::new);
     }
 
+    @Procedure("apoc.paths.toJsonTree")
+    @Description(
+            "apoc.paths.toJsonTree([paths],[lowerCaseRels=true], [config]) creates a stream of nested documents representing the at least one root of these paths")
```
Comment (JoelBergstrand) [inline core/src/main/java/apoc/convert/Json.java:236]: Would be good with different a different description for the new toTree so that it is possible to understand what the difference is.

**Review by JoelBergstrand — APPROVED** [review]
Great!
