### PR TITLE
Fixes #1744: Stored procedure error on neo4j restart

### LINKED ISSUE #1744: Stored procedure error on neo4j restart
## Expected Behavior (Mandatory)

No stack trace on database restart

## Actual Behavior (Mandatory)

After creating a stored procedure, when I restart the DB I get this error:
```
2020-12-03 08:28:15.542+0000 ERROR [neo4j] Could not register procedure: custom.vantagepoint_within_area with 
		MATCH (start:Area {name: $areaName} )
		CALL apoc.path.expand(start,'CONTAINS>|<SEES|CURRENT','',0,100) YIELD path
		UNWIND nodes(path) as node
		WITH node
		WHERE node:VantagePoint
		RETURN DISTINCT node 
	as resource accepting[areaName :: STRING?] resulting in [resource :: NODE?] mode READ
java.lang.UnsupportedOperationException 
	at java.base/java.util.AbstractCollection.add(AbstractCollection.java:267)
	at apoc.custom.CypherProceduresHandler.registerProcedure(CypherProceduresHandler.java:362)
	at apoc.custom.CypherProceduresHandler$ProcedureDescriptor.register(CypherProceduresHandler.java:661) at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:211)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:210)
	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:120)
	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126)
	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83)
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119)
	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) at org.neo4j.kernel.database.Database.start(Database.java:480)
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:134)
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:119)
	at com.neo4j.dbms.Transition$Prepared.doTransitionAction(Transition.java:101)
	at com.neo4j.dbms.Transition$Prepared.doTransition(Transition.java:88)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:347)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:348)
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:348)
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$11(DbmsReconciler.java:316)
	at com.neo4j.dbms.DbmsReconciler.namedJob(DbmsReconciler.java:327)
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:317)
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$9(DbmsReconciler.java:308)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I first thought it was related to having a 'dot' in the name because the name reported is incorrect in this case, but I changed to underscores and it still occurs.

### Simple Dataset (where it's possibile)

```
CALL apoc.custom.asProcedure('vantagepoint_within_area',
  "MATCH (start:Area {name: $areaName} )
    CALL apoc.path.expand(start,'CONTAINS>|<SEES|CURRENT','',0,100) YIELD path
    UNWIND nodes(path) as node
    WITH node
    WHERE node:VantagePoint
    RETURN DISTINCT node as resource",
  'read',
  [['resource','NODE']],
  [['areaName', 'STRING']],
  "Get vantage points within an area and all included areas");
```

### Steps (Mandatory)

  1. Create the procedure as above
  1. Restart Neo4J
  1. Observe the neo4j output

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux (Alpine in Docker)
  - Neo4j: neo4j:4.1.3-enterprise
  - Neo4j-Apoc: apoc-4.1.0.3-all.jar

### LINKED ISSUE #1871: apoc.custom.function error on startup
## Expected Behavior (Mandatory)

No error on startup for apoc.custom.*.   The function does not show up with a call to  apoc.custom.list()
## Actual Behavior (Mandatory)

Don't error.

## How to Reproduce the Problem

1. Take attached dump, unzip and load into a 4.2.5 Neo4j EE database (I used Neo4j Desktop to create this db)
1. Install apoc
1. Start db

### Simple Dataset (where it's possibile)

[contract-tracing-name-idx-neo4j-2021-04-26T214357.dump.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/6380772/contract-tracing-name-idx-neo4j-2021-04-26T214357.dump.zip)

### Steps (Mandatory)

1. Start db
2. Review logs/neo4j.log

## Screenshots (where it's possibile)

Initial relevant section of neo4j.log
```
2021-04-26 21:39:02.627+0000 INFO  Starting...
2021-04-26 21:39:05.482+0000 INFO  ======== Neo4j 4.2.5 ========
2021-04-26 21:39:10.533+0000 ERROR [neo4j/99376483] Could not register function: custom.debugQry(level = OFF :: STRING?, threshold = 0s :: STRING?, logsLogLevel = NONE :: STRING?) :: (STRING?)
with: CALL dbms.setConfigValue('dbms.logs.query.enabled', $level)
 CALL dbms.setConfigValue('dbms.logs.query.page_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.threshold', $threshold)
 CALL dbms.setConfigValue('dbms.logs.query.allocation_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.runtime_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.parameter_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.time_logging_enabled', 'TRUE')

 CALL dbms.setConfigValue('dbms.logs.debug.level', $logsLogLevel)

 CALL dbms.setConfigValue('dbms.track_query_allocation', 'TRUE')
 CALL dbms.setConfigValue('dbms.track_query_cpu_time', 'TRUE')
 RETURN [{level: $level}, {threshold: $threshold}, {logsLogLevel: $logsLogLevel}] AS res
 single result true
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:267) ~[?:?]
	at apoc.custom.CypherProceduresHandler.registerFunction(CypherProceduresHandler.java:410) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler$UserFunctionDescriptor.register(CypherProceduresHandler.java:686) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:212) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:211) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:120) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.database.Database.start(Database.java:511) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187) ~[neo4j-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:141) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:119) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransitionAction(Transition.java:101) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransition(Transition.java:88) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:355) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$12(DbmsReconciler.java:324) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.namedJob(DbmsReconciler.java:335) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:325) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$10(DbmsReconciler.java:310) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-26 21:39:12.006+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2021-04-26 21:39:19.478+0000 INFO  Sending metrics to CSV file at /Users/danflavin/Library/Application Support/com.Neo4j.Relate/Data/dbmss/dbms-9c3de7fb-c391-461c-8b77-2be30636f488/metrics
2021-04-26 21:39:19.529+0000 INFO  Bolt enabled on localhost:7687.
2021-04-26 21:39:20.651+0000 INFO  Remote interface available at http://localhost:7474/
2021-04-26 21:39:20.652+0000 INFO  Started.
2021-04-26 21:39:20.927+0000 INFO  Neo4j Server shutdown initiated by request
2021-04-26 21:39:20.927+0000 INFO  Stopping...
2021-04-26 21:39:26.809+0000 INFO  Stopped.
2021-04-26 21:39:45.584+0000 INFO  Starting...
2021-04-26 21:39:48.426+0000 INFO  ======== Neo4j 4.2.5 ========
2021-04-26 21:39:51.752+0000 ERROR [neo4j/99376483] Could not register function: custom.debugQry(level = OFF :: STRING?, threshold = 0s :: STRING?, logsLogLevel = NONE :: STRING?) :: (STRING?)
with: CALL dbms.setConfigValue('dbms.logs.query.enabled', $level)
 CALL dbms.setConfigValue('dbms.logs.query.page_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.threshold', $threshold)
 CALL dbms.setConfigValue('dbms.logs.query.allocation_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.runtime_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.parameter_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.time_logging_enabled', 'TRUE')

 CALL dbms.setConfigValue('dbms.logs.debug.level', $logsLogLevel)

 CALL dbms.setConfigValue('dbms.track_query_allocation', 'TRUE')
 CALL dbms.setConfigValue('dbms.track_query_cpu_time', 'TRUE')
 RETURN [{level: $level}, {threshold: $threshold}, {logsLogLevel: $logsLogLevel}] AS res
 single result true
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:267) ~[?:?]
	at apoc.custom.CypherProceduresHandler.registerFunction(CypherProceduresHandler.java:414) ~[apoc-4.2.0.2.jar:4.2.0.2]
	at apoc.custom.CypherProceduresHandler$UserFunctionDescriptor.register(CypherProceduresHandler.java:692) ~[apoc-4.2.0.2.jar:4.2.0.2]
	at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:214) ~[apoc-4.2.0.2.jar:4.2.0.2]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:213) ~[apoc-4.2.0.2.jar:4.2.0.2]
	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:120) ~[apoc-4.2.0.2.jar:4.2.0.2]
	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.database.Database.start(Database.java:511) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187) ~[neo4j-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:141) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:119) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransitionAction(Transition.java:101) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransition(Transition.java:88) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:355) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$12(DbmsReconciler.java:324) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.namedJob(DbmsReconciler.java:335) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:325) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$10(DbmsReconciler.java:310) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-26 21:39:53.125+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2021-04-26 21:40:07.389+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address.
java.lang.RuntimeException: Error starting Neo4j database server at /Users/danflavin/Library/Application Support/com.Neo4j.Relate/Data/dbmss/dbms-3944ce61-8fa4-4f02-b8d9-472601496be9/data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:207) ~[neo4j-4.2.5.jar:4.2.5]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:163) ~[neo4j-4.2.5.jar:4.2.5]
	at com.neo4j.server.enterprise.EnterpriseManagementServiceFactory.createManagementService(EnterpriseManagementServiceFactory.java:38) ~[neo4j-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:20) ~[neo4j-enterprise-4.2.5.jar:4.2.5]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:134) [neo4j-4.2.5.jar:4.2.5]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:90) [neo4j-4.2.5.jar:4.2.5]
	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:25) [neo4j-enterprise-4.2.5.jar:4.2.5]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.procedure.impl.GlobalProceduresRegistry@6537ac' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.generate.ba` is already in use.".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198) ~[neo4j-4.2.5.jar:4.2.5]
	... 6 more
Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: Unable to register procedure, because the name `apoc.generate.ba` is already in use.
	at org.neo4j.procedure.impl.ProcedureRegistry.register(ProcedureRegistry.java:93) ~[neo4j-procedure-4.2.5.jar:4.2.5]
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.register(GlobalProceduresRegistry.java:154) ~[neo4j-procedure-4.2.5.jar:4.2.5]
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.register(GlobalProceduresRegistry.java:94) ~[neo4j-procedure-4.2.5.jar:4.2.5]
	at org.neo4j.procedure.impl.GlobalProceduresRegistry.start(GlobalProceduresRegistry.java:386) ~[neo4j-procedure-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198) ~[neo4j-4.2.5.jar:4.2.5]
	... 6 more
2021-04-26 21:40:07.390+0000 INFO  Neo4j Server shutdown initiated by request
2021-04-26 21:40:07.390+0000 INFO  Stopped.
2021-04-26 21:41:55.168+0000 INFO  Starting...
2021-04-26 21:41:57.916+0000 INFO  ======== Neo4j 4.2.5 ========
2021-04-26 21:42:01.253+0000 ERROR [neo4j/99376483] Could not register function: custom.debugQry(level = OFF :: STRING?, threshold = 0s :: STRING?, logsLogLevel = NONE :: STRING?) :: (STRING?)
with: CALL dbms.setConfigValue('dbms.logs.query.enabled', $level)
 CALL dbms.setConfigValue('dbms.logs.query.page_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.threshold', $threshold)
 CALL dbms.setConfigValue('dbms.logs.query.allocation_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.runtime_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.parameter_logging_enabled', 'TRUE')
 CALL dbms.setConfigValue('dbms.logs.query.time_logging_enabled', 'TRUE')

 CALL dbms.setConfigValue('dbms.logs.debug.level', $logsLogLevel)

 CALL dbms.setConfigValue('dbms.track_query_allocation', 'TRUE')
 CALL dbms.setConfigValue('dbms.track_query_cpu_time', 'TRUE')
 RETURN [{level: $level}, {threshold: $threshold}, {logsLogLevel: $logsLogLevel}] AS res
 single result true
java.lang.UnsupportedOperationException: null
	at java.util.AbstractCollection.add(AbstractCollection.java:267) ~[?:?]
	at apoc.custom.CypherProceduresHandler.registerFunction(CypherProceduresHandler.java:410) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler$UserFunctionDescriptor.register(CypherProceduresHandler.java:686) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler.lambda$restoreProceduresAndFunctions$2(CypherProceduresHandler.java:212) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at apoc.custom.CypherProceduresHandler.restoreProceduresAndFunctions(CypherProceduresHandler.java:211) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at apoc.custom.CypherProceduresHandler.available(CypherProceduresHandler.java:120) ~[apoc-4.2.0.0.jar:4.2.0.0]
	at org.neo4j.internal.helpers.Listeners.notifySingleListener(Listeners.java:126) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.internal.helpers.Listeners.notify(Listeners.java:83) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:119) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:61) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110) ~[neo4j-common-4.2.5.jar:4.2.5]
	at org.neo4j.kernel.database.Database.start(Database.java:511) ~[neo4j-kernel-4.2.5.jar:4.2.5]
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187) ~[neo4j-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.forSingleDatabase(MultiDatabaseManager.java:141) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:119) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransitionAction(Transition.java:101) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.Transition$Prepared.doTransition(Transition.java:88) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:355) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitionStep(DbmsReconciler.java:356) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$12(DbmsReconciler.java:324) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.namedJob(DbmsReconciler.java:335) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.doTransitions(DbmsReconciler.java:325) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at com.neo4j.dbms.DbmsReconciler.lambda$doTransitions$10(DbmsReconciler.java:310) ~[neo4j-dbms-enterprise-4.2.5.jar:4.2.5]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-04-26 21:42:02.657+0000 INFO  Called db.clearQueryCaches(): Query cache already empty.
2021-04-26 21:42:10.392+0000 INFO  Sending metrics to CSV file at /Users/danflavin/Library/Application Support/com.Neo4j.Relate/Data/dbmss/dbms-3944ce61-8fa4-4f02-b8d9-472601496be9/metrics
2021-04-26 21:42:10.425+0000 INFO  Bolt enabled on localhost:7687.
2021-04-26 21:42:11.532+0000 INFO  Remote interface available at http://localhost:7474/
2021-04-26 21:42:11.533+0000 INFO  Started
```

## Specifications (Mandatory)

Code used to create function:
```
CALL apoc.custom.asFunction('debugQry',
'CALL dbms.setConfigValue(\'dbms.logs.query.enabled\', $level)
 CALL dbms.setConfigValue(\'dbms.logs.query.page_logging_enabled\', \'TRUE\')
 CALL dbms.setConfigValue(\'dbms.logs.query.threshold\', $threshold)
 CALL dbms.setConfigValue(\'dbms.logs.query.allocation_logging_enabled\', \'TRUE\')
 CALL dbms.setConfigValue(\'dbms.logs.query.runtime_logging_enabled\', \'TRUE\')
 CALL dbms.setConfigValue(\'dbms.logs.query.parameter_logging_enabled\', \'TRUE\')
 CALL dbms.setConfigValue(\'dbms.logs.query.time_logging_enabled\', \'TRUE\')

 CALL dbms.setConfigValue(\'dbms.logs.debug.level\', $logsLogLevel)

 CALL dbms.setConfigValue(\'dbms.track_query_allocation\', \'TRUE\')
 CALL dbms.setConfigValue(\'dbms.track_query_cpu_time\', \'TRUE\')
 RETURN [{level: $level}, {threshold: $threshold}, {logsLogLevel: $logsLogLevel}] AS res',
'RETURN res',
[['level', 'STRING', "'OFF'"], ['threshold', 'STRING', "'0s'"], ['logsLogLevel', 'STRING', "'NONE'"]],  TRUE, 'Set debug: RETURN custom.debugQry(\'VERBOSE\', \'0s\', \'INFO\')')
;
```

Currently used versions

### Versions

  - OS: mac osx Big Sur 11.2.3
  - Neo4j: 4.2.5
  - Neo4j-Apoc: 4.2.0.2

### PR DESCRIPTION
**Pull request by vga91**
Fixes #1744
Fixes #1871

- Added test emulating the issue 1744
- Changed `registeredProcedureSignatures` and `registeredUserFunctionSignatures ` from immutable to mutable Sets
- Simplified logic removing de-register on restoreProcedure and replacing with `registeredProcedureSignatures.remove(signature);` in `registerProcedure()` and `registeredUserFunctionSignatures.remove(signature);` in `registerFunction()`

### CODE REVIEW

File: full/src/main/java/apoc/custom/CypherProceduresHandler.java [hunk 1]
```diff
@@ -98,8 +98,8 @@
     private final JobScheduler jobScheduler;
     private long lastUpdate;
     private final ThrowingFunction<Context, Transaction, ProcedureException> transactionComponentFunction;
-    private Set<ProcedureSignature> registeredProcedureSignatures = emptySet();
-    private Set<UserFunctionSignature> registeredUserFunctionSignatures = emptySet();
+    private final Set<ProcedureSignature> registeredProcedureSignatures = Collections.synchronizedSet(new HashSet<>());
```
Comment (fbiville) [inline full/src/main/java/apoc/custom/CypherProceduresHandler.java:101]: how does this get populated when the DB starts?

**Review by fbiville — APPROVED** [review]

File: full/src/main/java/apoc/custom/CypherProceduresHandler.java (hunk 1 above)
Comment (vga91) [reply full/src/main/java/apoc/custom/CypherProceduresHandler.java:101]: In `available()` method, called after each reboot, through the `restoreProceduresAndFunctions()`, where it is populated based on System nodes.
