### PR TITLE
fixes: #1253: Add support for gs:// file prefix for Google Cloud Storage

### LINKED ISSUE #1253: Add support for gs:// file prefix for Google Cloud Storage
## Feature description (Mandatory)
Apoc supports s3:// to read/write files to  AWS S3 storage but it doesn’t support the equivalent Google Cloud Storage gs://

Both cloud storage services provide java libraries that use the hdfs interface so it should be not too hard to add gs://

There is more info on gs:// here:
https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1253 
One sentence summary of the change.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added support for `gs://` protocol

### CODE REVIEW

File: src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+        return blob.getContentType();
+    }
+
+    @Override
+    public InputStream getInputStream() throws IOException {
+        if (!connected) {
+            connect();
+        }
+        byte[] data;
+        if (blob == null) {
```
Comment (jexp) [inline src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java]: is there no streaming way too read the content?

Comment (jexp) [reply src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java]: e.g. via 
https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/storage/Blob.html#downloadTo-java.io.OutputStream-com.google.cloud.storage.Blob.BlobSourceOption...-

or 

https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/storage/Blob.html#reader-com.google.cloud.storage.Blob.BlobSourceOption...-

File: docs/asciidoc/import/webapis.adoc [hunk 2]
```diff
@@ -62,6 +62,52 @@ or
 * `s3://endpoint:port/bucket/key?accessKey=accessKey&secretKey=secretKey`
 
 
+== Using Google Cloud Storage
+
+In order to use Google Cloud Storage you need that the following jars are included into the plugin dir:
+
+* api-common-1.8.1.jar
```
Comment (jexp) [inline docs/asciidoc/import/webapis.adoc]: lots of jars, can we look into providing a module that generates an uber jar for these? that we can make available?

File: src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+    }
+
+    @VisibleForTesting
+    public Storage getStorage(URI uri) {
+        Storage storage;
+        Map<String, String> queryParams = getQueryParams(uri);
+        AuthType authenticationType = AuthType.valueOf(queryParams.getOrDefault("authenticationType", AuthType.NONE.toString()));
+        switch (authenticationType) {
+            case SERVICE:
+                String googleAppCredentialsEnv = System.getenv("GOOGLE_APPLICATION_CREDENTIALS");
```
Comment (jexp) [inline src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java]: can't it be passed in other means? e.g. in server setups those might not be settable?

File: src/test/java/apoc/load/LoadGoogleCloudStorageTest.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+    private static final String BUCKET_NAME = System.getenv("APOC_GC_BUCKET_NAME");
+
+    @BeforeClass
+    public static void before() {
+        Assume.assumeNotNull(BUCKET_NAME);
+    }
+
+    @Before
+    public void setUp() throws Exception {
+        db = new TestGraphDatabaseFactory().newImpermanentDatabaseBuilder()
```
Comment (jexp) [inline src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: do we need file import enabled for remote loads, I'm not sure how we do it with other options?

File: src/test/java/apoc/load/LoadGoogleCloudStorageTest.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+import static apoc.load.LoadCsvTest.assertRow;
+import static apoc.util.MapUtil.map;
+import static apoc.util.TestUtil.testResult;
+import static org.junit.Assert.assertFalse;
+
+public class LoadGoogleCloudStorageTest {
+
+    private GraphDatabaseService db;
+
+    private static final String BUCKET_NAME = System.getenv("APOC_GC_BUCKET_NAME");
```
Comment (jexp) [inline src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: where does this come from?

Comment (jexp) [reply src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: Is this something we can set up dynamically?

File: docs/asciidoc/import/webapis.adoc (hunk 2 above)
Comment (conker84) [reply docs/asciidoc/import/webapis.adoc]: I created this issue #1297

File: src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java (hunk 3 above)
Comment (conker84) [reply src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java]: As the first implementation, I tried to stick to the best practice, but I added the authentication type because as you underscored there can be someone that uses an alternative way to authenticate to the service, so we can improve that in a community-driven way. WDYT?

File: src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java (hunk 1 above)
Comment (conker84) [reply src/main/java/apoc/util/google/cloud/GCStorageURLConnection.java]: Ok!

File: src/test/java/apoc/load/LoadGoogleCloudStorageTest.java (hunk 4 above)
Comment (conker84) [reply src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: It's not necessary, I'll remove it

File: src/test/java/apoc/load/LoadGoogleCloudStorageTest.java (hunk 5 above)
Comment (conker84) [reply src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: Unfortunately (as the result of my investigation) there is no Docker container or java library that allows testing the connection to a Google Storage Bucket. The only way to do that at this moment is to connect to a real bucket. So I used my private bucket to test it. I thought that we can use an env variable so into Travis we can easily inject a bucket.

Comment (jexp) [reply src/test/java/apoc/load/LoadGoogleCloudStorageTest.java]: ok
