### PR TITLE
fixes #1181: APOC 3.5.0.3 changes import file URL paths too aggressively

### LINKED ISSUE #1181: APOC 3.5.0.3 changes import file URL paths too aggressively
## Expected Behavior (Mandatory)

```
call apoc.metrics.get("neo4j.bolt.sessions_started");
```

Should return metric data in Neo4j Desktop installations.

## Actual Behavior (Mandatory)

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.metrics.get`: 

Caused by: java.io.FileNotFoundException: 
/Users/davidallen/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-6df59434-8fe6-405c-ab17-dd0a913b1498/installation-3.5.4/import/Users/davidallen/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-6df59434-8fe6-405c-ab17-dd0a913b1498/installation-3.5.4/metrics/neo4j.bolt.sessions_started.csv 
(No such file or directory)
```

## How to Reproduce the Problem

(Run above query)

## Cause

In `apoc.metrics.Metrics.loadCsvForMetric`, great care is taken to build an absolute directory reference to the location of metrics, taking into account neo4j config.  This is done by `FileUtils.getMetricsDirectory`.    But when this absolute URL gets passed to the LoadCsv methods, it appears to use `FileUtils.changeFileUrlIfImportDirectoryConstrained` which seems to be appending the absolute directory as a relative to the import path.

The result is an ultra-long local URL which is wrong, causing the file not to exist, causing the metrics load to fail.

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1181

Fixed the bug and created a Test case with Testcontainers

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - fixed the bug
  - created the testing class `MetricsTest`

### CODE REVIEW

File: src/main/java/apoc/metrics/Metrics.java [hunk 1]
```diff
@@ -162,10 +166,18 @@ public boolean test(LoadCsv.CSVResult o) {
                     "https://neo4j.com/docs/operations-manual/current/monitoring/metrics/expose/#metrics-csv");
         }
 
-        String url = new File(metricsDir, metricName + ".csv").toURI().toString();
```
Comment (jexp) [inline src/main/java/apoc/metrics/Metrics.java]: What is the difference that makes it not fail with the new, more restrictive config setting?

File: src/main/java/apoc/util/FileUtils.java [hunk 2]
```diff
@@ -260,4 +260,10 @@ public static boolean inNeo4jOwnedDirectory(File f) throws IOException {
             "dbms.directories.tx_log",
             "unsupported.dbms.directories.neo4j_home"
     );
+
+    public static void closeReaderSafely(CountingReader reader) {
```
Comment (jexp) [inline src/main/java/apoc/util/FileUtils.java]: couldn't have a try-with-resource done the same? just curious

**Comment by jexp** [comment]
Not 100% sure what changed to make it work now, but otherwise looks good to me.

File: src/main/java/apoc/metrics/Metrics.java [hunk 3]
```diff
@@ -162,10 +166,18 @@ public boolean test(LoadCsv.CSVResult o) {
...
+        String url = new File(metricsDir, metricName + ".csv").getAbsolutePath();
+        CountingReader reader = null;
+        try {
+            reader = FileUtils.readFile(url);
+            return new LoadCsv()
+                    .streamCsv(url, new LoadCsvConfig(config), reader)
+                    .filter(Metrics.duplicatedHeaderRows)
+                    .map(csvResult -> new GenericMetric(metricName, Util.toLong(csvResult.map.get("t")), csvResult.map));
+        } catch (Exception e) {
+            closeReaderSafely(reader);
```
Comment (moxious) [inline src/main/java/apoc/metrics/Metrics.java]: does reader get closed if an exception was not thrown?   Seems like this would be better in finally?

File: src/main/java/apoc/load/LoadCsv.java [hunk 4]
```diff
@@ -39,30 +41,35 @@
...
+        CSVReader csv = new CSVReaderBuilder(reader)
+                .withCSVParser(new CSVParserBuilder()
+                        .withQuoteChar(config.getQuoteChar())
+                        .withSeparator(config.getSeparator())
+                        .build())
+                .build();
+
+        String[] header = getHeader(csv, config);
+        boolean checkIgnore = !config.getIgnore().isEmpty() || config.getMappings().values().stream().anyMatch(m -> m.ignore);
+        return StreamSupport.stream(new CSVSpliterator(csv, header, url, config.getSkip(), config.getLimit(),
```
Comment (moxious) [inline src/main/java/apoc/load/LoadCsv.java]: not in scope of this PR but yikes that's a lot of arguments CSVSpliterator takes.  Might want to figure out how to simplify that object at some point.

File: src/test/java/apoc/metrics/MetricsTest.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+            neo4jContainer.close();
+        }
+        cleanBuild();
+    }
+
+    @Test
+    public void shouldGetMetrics() {
+        session.readTransaction(tx -> tx.run("RETURN 1 AS num;"));
+        String metricKey = "neo4j.bolt.sessions_started";
+        testResult(session, "CALL apoc.metrics.get({metricKey})",
```
Comment (moxious) [inline src/test/java/apoc/metrics/MetricsTest.java]: nice!  This is basically the test I wish I could have written with the original code, but we needed testcontainers.

File: src/main/java/apoc/load/LoadCsv.java (hunk 4 above)
Comment (jexp) [reply src/main/java/apoc/load/LoadCsv.java]: probably just pass the config :)

File: src/main/java/apoc/util/FileUtils.java (hunk 2 above)
Comment (conker84) [reply src/main/java/apoc/util/FileUtils.java]: good question my initial implementation was with a `try-with-resource`:
https://github.com/conker84/neo4j-apoc-procedures/commit/e41b338778432ceb1f7c050044ff4e4a08ab2af7#diff-fc68dee7028a27c02a83473c5e03ca44R167

But a test did by @moxious returned this exception:
```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.metrics.get`: Caused by: java.io.IOException: Stream closed
```

So in order to fix it, I removed the `try-with-resource` and closed it as the stream closes

File: src/main/java/apoc/metrics/Metrics.java (hunk 3 above)
Comment (conker84) [reply src/main/java/apoc/metrics/Metrics.java]: good question, it's only here because of the `streamCsv` method closes the reader as the stream closes:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/62cb555123757e4384280246233ca0ce5539feb5/src/main/java/apoc/load/LoadCsv.java#L70

So I need to manage it only in case of the exception.
But we can change it if you want

File: src/main/java/apoc/load/LoadCsv.java (hunk 4 above)
Comment (conker84) [reply src/main/java/apoc/load/LoadCsv.java]: yep

File: src/main/java/apoc/metrics/Metrics.java (hunk 1 above)
Comment (conker84) [reply src/main/java/apoc/metrics/Metrics.java]: The old way leverages directly the `LoadCsv#csv` method which uses `FileUtils#readerFor` and it internally uses:
`FileUtils#changeFileUrlIfImportDirectoryConstrained` which is the cause of the issue; so I created the `LoadCsv#streamCsv` method that thakes a reader in input.
