### PR TITLE
fixes #1840: [TRIGGER] createdRelationships after crash and afterAsync do nothing

### LINKED ISSUE #1840: [TRIGGER] createdRelationships "after" crash and "afterAsync" do nothing
## Expected Behavior (Mandatory)

When we add a trigger on `createdRelationships`, it should be executed wether we are in before, after or afterAsync phase.

## Actual Behavior (Mandatory)

The trigger on the phase before work, the same trigger on the phase after loop forever and on the phase afterAsync it does nothing.

## How to Reproduce the Problem

I have created a new db with dedicated node/relationship to reproduce the issue. See below :

### Simple Dataset (where it's possibile)

```
// TEST 1. populate DB
CREATE (:A {name: "A"})-[:R1]->(:Z {name: "Z"})

// TEST 2.1 add trigger before
CALL apoc.trigger.add('trigger-before', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerBefore = true', {phase: 'before'})

// TEST 2.2 add trigger after
CALL apoc.trigger.add('trigger-after', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerAfter = true', {phase: 'after'})

// TEST 2.3 add trigger after async
CALL apoc.trigger.add('trigger-after-async', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerAfterAsync = true', {phase: 'afterAsync'})

// TEST 3. (:A)-[:R2]->(:Z)
MATCH (a:A {name: "A"})-[:R1]->(z:Z {name: "Z"})
MERGE (a)-[:R2]->(z)

// TEST 4. get so data
MATCH (n1)-[r]->(n2) RETURN r, n1, n2 LIMIT 25

// TEST 5. clear DB
MATCH (n) DETACH DELETE n

// TEST 6. remove triggers
CALL apoc.trigger.removeAll()
```

### Steps (Mandatory)

  1. Populate the db TEST 1.
  1. Add 1 (or many) of the trigger provided in TEST 2.X
  1. execute TEST 3. to create the new relationship
  1. check the data, clean the db and remove triggers to retry

## Screenshots (where it's possibile)
Testing before :
image

Testing after :
image

Testing afterAsync : 
image

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 10 Family 19041.867
  - Neo4j: 4.2.4
  - Neo4j-Apoc: 4.2.0.2

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1840

The `afterAsync` phase needs to rebind the entities

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Fixed the bug
  - Added test

### CODE REVIEW

File: core/src/main/java/apoc/trigger/TriggerMetadata.java [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+            txId = -1L;
+        }
+        try {
+            commitTime = txData.getCommitTime();
+        } catch (Exception ignored) {
+            commitTime = -1L;
+        }
+        List<Node> createdNodes = Convert.convertToList(txData.createdNodes());
+        List<Relationship> createdRelationships = Convert.convertToList(txData.createdRelationships());
+        List<Node> deletedNodes = Convert.convertToList(txData.deletedNodes());
```
Comment (sarmbruster) [inline core/src/main/java/apoc/trigger/TriggerMetadata.java:76]: I'm not confident that rebind on deleted entities actually works. Can we please ensure we have a test case that runs deletions and validates rebind on those workds?

Comment (conker84) [reply core/src/main/java/apoc/trigger/TriggerMetadata.java]: You're right, for these cases I converted them to Virtual Entities, so we can use them

Comment (sarmbruster) [reply core/src/main/java/apoc/trigger/TriggerMetadata.java]: LGFM now, please feel free to merge. Thanks.
