### PR TITLE
Fixes #2015: Various bugs with Neo4j 4.3 indexes

### LINKED ISSUE #2015: Various bugs with Neo4j 4.3 indexes
With relationship and lookup indexes, there are some problems:

### Steps (Mandatory)

1. `apoc.meta.data` the relations give `indexed = false` even if there are indexes
2. `apoc.meta.schema` there isn't the `indexed` field with relationships
3. `apoc.schema.nodes` displays both indexes on nodes and relations, while `apoc.schema.relationships` does not display indexes
4. `apoc.schema.assert` does not delete rel indexes
5. The `LOOKUP` indexes are never considered

### Versions

  - OS: Mac Big Sur
  - Neo4j: 4.3
  - Neo4j-Apoc: 4.3.0.0

### PR DESCRIPTION
**Pull request by vga91**
Fixes #2015

- Implemented `getIndexes(RelationshipType type)` in `SubGraph.java`
- Added `relIndexes` in `Meta.java`
- Added lookup index handling

### CODE REVIEW

File: core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java [hunk 1]
```diff
@@ -205,6 +205,13 @@ public boolean contains( Relationship relationship )
                 .collect(Collectors.toSet());
     }
 
+    @Override
+    public Iterable<IndexDefinition> getIndexes(RelationshipType type) {
+        return indexes.stream()
+                .filter(idx -> StreamSupport.stream(idx.getRelationshipTypes().spliterator(), false).anyMatch(lb -> lb.equals(type)))
```
Comment (jexp) [inline core/src/main/java/org/neo4j/cypher/export/CypherResultSubGraph.java:211]: should probably do equals on the name() to be sure, because RelationshipType is an interface so there is no symmetric equals

**Review by jexp — APPROVED** [review]
Great PR! Thanks a lot
