### PR TITLE
Fixes #2034: The procedure apoc.cypher.mapParallel2 sometime fails with Unable to complete transaction error

### LINKED ISSUE #2034: The procedure `apoc.cypher.mapParallel2` sometime fails with "Unable to complete transaction" error
## Expected Behavior (Mandatory)

The procedure always works

## Actual Behavior (Mandatory)

Sometimes we obtain an `Unable to complete transaction` error.

## How to Reproduce the Problem

```
UNWIND range(1, 100) as i create (p:Page {title: i})-[:Link]->(p1:Page1)<-[:Link]-(p2:Page2 {title: 'myTitle'});
```

```
MATCH (p:Page) WITH collect(p) as pages
CALL apoc.cypher.mapParallel2("MATCH (_)-[:Link]->(p1)<-[:Link]-(p2)
RETURN  p2.title as title", {}, pages, 1) yield value
RETURN value.title limit 5
```

### Versions

  - OS: Mac BigSur
  - Neo4j: 4.3
  - Neo4j-Apoc: 4.3.0.0

### PR DESCRIPTION
**Pull request by vga91**
Fixes #2034

### CODE REVIEW

File: full/src/test/java/apoc/cypher/CypherExtendedTest.java [hunk 1]
```diff
@@ -160,6 +160,19 @@ public void testRunFileWithResults() throws Exception {
                     assertEquals(false, r.hasNext());
                 });
     }
+
+    @Test
+    public void shouldNotFailWithTransactionErrorWithMapParallel2() {
+        // Flaky test. Sometimes it's green even without `db.beginTx()` modification
```
Comment (fbiville) [inline full/src/test/java/apoc/cypher/CypherExtendedTest.java:166]: it's not flaky anymore with the fix, is it?

**Review by fbiville — APPROVED** [review]

File: full/src/test/java/apoc/cypher/CypherExtendedTest.java (hunk 1 above)
Comment (vga91) [reply full/src/test/java/apoc/cypher/CypherExtendedTest.java]: Of course, it was confusing. Changed.
