### PR TITLE
fixes #1488 and #1489: Export XLS improvements

### LINKED ISSUE #1488: apoc.export.xls.* breaks when the relationship has the same name as label
`apoc.export.xls.*` breaks when the relationship has the same name as label.

## Expected Behavior (Mandatory)

Should import the data

## Actual Behavior (Mandatory)

The procedure throws an exception:

```
org.neo4j.graphdb.QueryExecutionException: Failed to invoke procedure `apoc.export.xls.graph`: Caused by: java.lang.IllegalArgumentException: The workbook already contains a sheet named 'COMPANY'

```

### Simple Dataset (where it's possibile)

```
CREATE (u:User{name: 'Andrea'})-[r:COMPANY{since: 2018}]->(c:Company{name: 'Larus'})
```

### Steps (Mandatory)

```java
    @Test
    public void testExportQueryXlsWithSameLabelAndRelName() throws Exception {
        db.executeTransactionally("CREATE (u:User{name: 'Andrea'})-[r:COMPANY{since: 2018}]->(c:Company{name: 'Larus'})");
        String fileName = "query.xlsx";
        TestUtil.testCall(db, "CALL apoc.graph.fromCypher($query, {}, '', {}) YIELD graph AS exportedGraph " +
                        "CALL apoc.export.xls.graph(exportedGraph, $file, {}) YIELD file, source, format, time " +
                        "RETURN *",
                map("file", fileName,
                        "query", "MATCH (u:User{name: 'Andrea'})-[r:COMPANY]->(c:Company{name: 'Larus'}) return *"),
                (r) -> {
                    assertTrue("Should get statement",r.get("source").toString().equals("graph: nodes(2), rels(1)"));
                    assertEquals(fileName, r.get("file"));
                    assertEquals("xls", r.get("format"));
                });
        assertSheets(fileName, 3);
    }
```

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1488 and #1489

One sentence summary of the change.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

For #1488 
- I added a new config param `prefixSheetWithEntityType` that prefix the sheet with the entity type `Node-` / `Rel-`

For #1489 
- I added a new config param `joinLabels` that joint labels for the sheet name (ie `:User:Customer`, become `User,Customer`)

### CODE REVIEW

**Comment by mneedham** [comment]
@conker84 why don't we just do that prefixing and joining of labels anyway and not bother with the extra config params?

File: src/test/java/apoc/export/csv/ExportXlsTest.java [hunk 1]
```diff
@@ -154,9 +140,9 @@ private void assertExcelFileForGraph(String fileName) {
             Workbook wb = WorkbookFactory.create(inp);
 
             int numberOfSheets = wb.getNumberOfSheets();
-            assertEquals(Iterables.count(tx.getAllLabels()) + Iterables.count(tx.getAllRelationshipTypes()), numberOfSheets);
+            assertEquals(Iterables.count(tx.getAllLabelsInUse()) + Iterables.count(tx.getAllRelationshipTypesInUse()), numberOfSheets);
```
Comment (mneedham) [inline src/test/java/apoc/export/csv/ExportXlsTest.java:143]: is this an unrelated change?

Comment (conker84) [reply src/test/java/apoc/export/csv/ExportXlsTest.java:143]: It's releated because at line 110 I create new labels `Customer` & `Company`, this makes fail the other tests now

**Comment by conker84** [comment]
> @conker84 why don't we just do that prefixing and joining of labels anyway and not bother with the extra config params?

I used the config params so it's backwards compatible, because the defaults replicate the behaviour as-is.
