### PR TITLE
fix #1071 apoc.periodic.commit should check for `limit`

### LINKED ISSUE #1071: apoc.periodic.commit should check for `limit`
if the statement passed in as an argument does not contain the word `limit`, it should fail with a reasonable error message.

### PR DESCRIPTION
**Pull request by sarmbruster**
This - of course - is a somewhat breaking changes. Usages that do not have a `limit` will get an exception.

### CODE REVIEW

File: src/main/java/apoc/periodic/Periodic.java [hunk 1]
```diff
@@ -49,11 +50,15 @@
 
     @Procedure(mode = Mode.WRITE)
     @Description("apoc.periodic.commit(statement,params) - runs the given statement in separate transactions until it returns 0")
-    public Stream<RundownResult> commit(@Name("statement") String statement, @Name("params") Map<String,Object> parameters) throws ExecutionException, InterruptedException {
+    public Stream<RundownResult> commit(@Name("statement") String statement, @Name(value = "params", defaultValue = "") Map<String,Object> parameters) throws ExecutionException, InterruptedException {
         Map<String,Object> params = parameters == null ? Collections.emptyMap() : parameters;
         long total = 0, executions = 0, updates = 0;
         long start = nanoTime();
 
+        if (!StringUtils.containsIgnoreCase(statement, "limit")) {
```
Comment (jexp) [inline src/main/java/apoc/periodic/Periodic.java]: perhaps with white-spaces around it?

File: src/main/java/apoc/periodic/Periodic.java [hunk 2]
```diff
@@ -49,11 +50,15 @@
 
     @Procedure(mode = Mode.WRITE)
     @Description("apoc.periodic.commit(statement,params) - runs the given statement in separate transactions until it returns 0")
```
Comment (jexp) [inline src/main/java/apoc/periodic/Periodic.java]: should we document that it needs a `LIMIT $limit` ?

Comment (sarmbruster) [reply src/main/java/apoc/periodic/Periodic.java]: Agreed. Will fix this.

File: src/main/java/apoc/periodic/Periodic.java (hunk 1 above)
Comment (sarmbruster) [reply src/main/java/apoc/periodic/Periodic.java]: Agreed. Will fix this.
