### PR TITLE
fixes #1424: ApocConfig does not load neo4j.conf properly if dir contains whitespace

### LINKED ISSUE #1424: ApocConfig does not load neo4j.conf properly if dir contains whitespace
This test fails

```Java
    @Test
    public void testDetermineNeo4jConfFolderWithWhitespaces() {
        System.setProperty(SUN_JAVA_COMMAND, "com.neo4j.server.enterprise.CommercialEntryPoint --config-dir=/home/stefan/neo4j enterprise-4.0.0-alpha09mr02/conf --home-dir=/home/stefan/neo4j enterprise-4.0.0-alpha09mr02");

        assertEquals("/home/stefan/neo4j enterprise-4.0.0-alpha09mr02/conf", cut.determineNeo4jConfFolder());
    }
```

### PR DESCRIPTION
**Pull request by conker84**
Fixes #1424

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - changed parsing of the neo4j.conf dir
  - added test

### CODE REVIEW

File: src/main/java/apoc/ApocConfig.java [hunk 1]
```diff
@@ -46,6 +46,7 @@
 
     public static final String SUN_JAVA_COMMAND = "sun.java.command";
     public static final Pattern CONF_DIR_PATTERN = Pattern.compile("--config-dir=(\\S+)");
```
Comment (sarmbruster) [inline src/main/java/apoc/ApocConfig.java]: That line can be removed when we get rid of regex.

Comment (conker84) [reply src/main/java/apoc/ApocConfig.java]: done

Comment (sarmbruster) [reply src/main/java/apoc/ApocConfig.java]: Thanks
