### PR TITLE
Fixes #1555 and #1558 

### LINKED ISSUE #1555: apoc.custom.asProcedure doesn't overwrite existing procedure by same name
## To reproduce
I'll use the example of the documentation

Execute this twice
`CALL apoc.custom.asProcedure('neighbours',
  'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour','read',
  [['neighbour','NODE']],[['name','STRING']], 'get neighbours of a person');
`
then `CALL apoc.custom.list`

## Expected Behavior
(Assuming clean db) lists one procedure with name 'neighbours'

## Actual Behavior
 (Assuming clean db) lists two procedures with name 'neighbours'

##
You also can't remove the procedure with `CALL apoc.custom.removeProcedure('neighbours')` because that expects there to only be one record for that name and it freaks out when many are returned.

Also when restarting the db errors get logged, I suspect, for attempts of registering procedure of the same name repeatedly.

So there's two things to fix:

- `apoc.custom.asProcedure` to owerwrite existing procedures
- `apoc.custom.removeProcedure` to delete all "procedures" of name (to allow affected users fix their databases)

P.S. Maybe `apoc.custom.asFunction` has same issue, haven't checked.

### Versions

  - OS: Ubuntu 18.04
  - Neo4j: 4.0.4
  - Neo4j-Apoc: 4.0.0.15

### PR DESCRIPTION
**Pull request by augonis**
Fixes #1555 and #1558 
Fixes the issue and enables repairs for affected users

## Proposed Changes
 - Fix typo in `Util.mergeNode` (cause of the issues)
 - Let `apoc.custom.removeProcedure` and `apoc.custom.removeFunction` handle existence of multiple records of procedure/function with same name

### CODE REVIEW

File: src/main/java/apoc/custom/CypherProceduresHandler.java [hunk 1]
```diff
@@ -598,30 +598,32 @@ private AnyValue convertToValueRecursive(Object... toConverts) {
 
     public void removeProcedure(String name) {
         withSystemDb(tx -> {
-            Node node = Iterators.single(tx.findNodes(SystemLabels.ApocCypherProcedures,
+            tx.findNodes(SystemLabels.ApocCypherProcedures,
```
Comment (conker84) [inline src/main/java/apoc/custom/CypherProceduresHandler.java:601]: This should be not necessary.

File: src/main/java/apoc/custom/CypherProceduresHandler.java [hunk 2]
```diff
@@ -598,30 +598,32 @@ private AnyValue convertToValueRecursive(Object... toConverts) {
...
+                setLastUpdate(tx);
+            });
             return null;
         });
     }
 
     public void removeFunction(String name) {
         withSystemDb(tx -> {
-            Node node = Iterators.single(tx.findNodes(SystemLabels.ApocCypherProcedures,
+            tx.findNodes(SystemLabels.ApocCypherProcedures,
```
Comment (conker84) [inline src/main/java/apoc/custom/CypherProceduresHandler.java:617]: This should be not necessary as well

**Comment by augonis** [comment]
The changes to `removeProcedure` and `removeFunction` are needed to allow users already affected by the issue fix their damaged databases. Can you propose an alternative way of removing the existing duplicate procedure/function?

File: src/main/java/apoc/custom/CypherProceduresHandler.java (hunk 1 above)
Comment (augonis) [reply src/main/java/apoc/custom/CypherProceduresHandler.java:601]: We can no longer assume there will no more than one result, because there are databases out in the wilds affected by #1555 that have multiple records with same name

File: src/main/java/apoc/custom/CypherProceduresHandler.java (hunk 2 above)
Comment (augonis) [reply src/main/java/apoc/custom/CypherProceduresHandler.java:617]: We can no longer assume there will no more than one result, because there are databases out in the wilds affected by #1558 that have multiple records with same name

File: src/test/java/apoc/custom/CypherProceduresTest.java [hunk 3]
```diff
@@ -258,6 +258,22 @@ public void shouldRemoveTheCustomFunction() throws Exception {
         TestUtil.count(db, "return custom.answer()");
     }
 
+    @Test
+    public void shouldOverwriteAndRemoveCustomProcedure() throws Exception {
+        db.executeTransactionally("call apoc.custom.asProcedure('answer','RETURN 42')");
+        db.executeTransactionally("call apoc.custom.asProcedure('answer','RETURN 42')");
+        assertEquals("Expecting one procedure listed", 1, TestUtil.count(db, "call apoc.custom.list()"));
```
Comment (conker84) [inline src/test/java/apoc/custom/CypherProceduresTest.java:265]: Can you also add a test for the system db that checks if there is more than 1 node?

File: src/test/java/apoc/custom/CypherProceduresTest.java [hunk 4]
```diff
@@ -258,6 +258,22 @@ public void shouldRemoveTheCustomFunction() throws Exception {
...
+        db.executeTransactionally("call apoc.custom.removeProcedure('answer')");
+    }
+
+    @Test
+    public void shouldOverwriteAndRemoveCustomFunction() throws Exception {
+        db.executeTransactionally("call apoc.custom.asFunction('answer','RETURN 42','long')");
+        db.executeTransactionally("call apoc.custom.asFunction('answer','RETURN 42','long')");
+        assertEquals("Expecting one function listed", 1, TestUtil.count(db, "call apoc.custom.list()"));
```
Comment (conker84) [inline src/test/java/apoc/custom/CypherProceduresTest.java:273]: Same as above

File: src/test/java/apoc/custom/CypherProceduresTest.java (hunk 3 above)
Comment (augonis) [reply src/test/java/apoc/custom/CypherProceduresTest.java:265]: You mean like a separate test (what exatcly I would be testing? Unit test for `Util.mergeNode?`) or just a new assertions in these tests?

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresTest.java:265]: No I mean a new assertion for this test that checks into the system db if there is just one node for the procedure/function as we removed the `Iterators.single` now would be better have a direct check into the system db

Comment (augonis) [reply src/test/java/apoc/custom/CypherProceduresTest.java:265]: `assertEquals("Expecting one procedure listed", 1, TestUtil.count(db, "call apoc.custom.list()"));` already does that, just indirectly.
And to do the check I would be more or less copying the implementation of `CypherProceduresHandler.readSignatures`, I'm not that comfortable querying db in code (no cypher) to write a bespoke query for the test.

Comment (conker84) [reply src/test/java/apoc/custom/CypherProceduresTest.java:265]: ok so let's leave it as is

**Comment by conker84** [comment]
LGTM thank you so much @augonis for this

**Comment by philastrophist** [comment]
What do I have to do if I need to remove a duplicated procedure with `apoc-4.2.0.0-all` on my live database? Is there a way to do this without apoc?

Thanks

**Comment by augonis** [comment]
Well, looks like this pull request was merged into a dead end branch (I can't find any release including it)  .
You could build your own patched version of apoc to include my fix.

**Comment by philastrophist** [comment]
ah, that's why...

Ok, I'll submit a issue. In the mean time, I'll do as you say. But is there really no way to remove an apoc procedure without apoc?
