### PR TITLE
fixes #810 - apoc.convert.toTree returns invalid data?

### LINKED ISSUE #810: apoc.convert.toTree returns invalid data?
I have a simple scenario with users flagging posts and comments.
When converting to nodes and flag-relations to a tree, the flag-properties come out wrong.

In my testing it appears like this:
If a user has flagged two different comments on the same post...
...then in the tree-structure the properties of those flags come out identical, although they should be different.

In the testing I used two different users, with one flag each on each of the two comments.

Here's the code:

The actual data for a post, with comments and flags:
MATCH (:Bib{id: '57523a6f-fda9-4a61-c4f6-08d47cdcf0cd'})-[:Has]->(:Comm)<-[f:Flag]-(:User)
return *

The result:

```
╒════════════════════════════════════════════════════════════╕
│"f"                                                         │
╞════════════════════════════════════════════════════════════╡
│{"FlagType":6,"Text":"asdf","Created":"2018-05-17T11:51:03"}│
├────────────────────────────────────────────────────────────┤
│{"FlagType":3,"Text":"","Created":"2018-05-17T11:37:59"}    │
├────────────────────────────────────────────────────────────┤
│{"FlagType":5,"Text":"","Created":"2018-05-17T11:51:00"}    │
├────────────────────────────────────────────────────────────┤
│{"Text":"","FlagType":2,"Created":"2018-05-17T11:47:49"}    │
└────────────────────────────────────────────────────────────┘

Now, with apoc.convert.toTree:
MATCH (parent:Bib {id: '57523a6f-fda9-4a61-c4f6-08d47cdcf0cd'})
WITH parent
OPTIONAL MATCH childFlagPath=(parent)-[:Has]->(:Comm)<-[:Flag]-(:User)
WITH COLLECT(childFlagPath) AS cfp
CALL apoc.convert.toTree(cfp) yield value as childrenUserFlags

RETURN {
childrenUserFlags: childrenUserFlags
}

The result:
{
  "childrenUserFlags": {
    "_type": "Bib",
    "_id": 124,
    "id": "57523a6f-fda9-4a61-c4f6-08d47cdcf0cd",
    "has": [
      {
        "_type": "Comm",
        "_id": 300,
        "id": "e9bbd508-23e5-0937-882a-a2c4d9e1feed",
        "flag": [
          {
            "_type": "User",
            "flag.Created": "2018-05-17T11:51:00",
            "_id": 55,
            "id": "google-oauth2|103969773122828433427",
            "flag.FlagType": 5,
            "flag.Text": ""
          },
          {
            "_type": "User",
            "flag.Created": "2018-05-17T11:47:49",
            "_id": 40,
            "id": "facebook|680594762097202",
            "flag.FlagType": 2,
            "flag.Text": ""
          }
        ]
      },
      {
        "_type": "Comm",
        "_id": 299,
        "id": "e9bbd508-15e2-338f-882a-a2c4d9e1feec",
        "flag": [
          {
            "_type": "User",
            "flag.Created": "2018-05-17T11:51:00",
            "_id": 55,
            "id": "google-oauth2|103969773122828433427",
            "flag.FlagType": 5,
            "flag.Text": ""
          },
          {
            "_type": "User",
            "flag.Created": "2018-05-17T11:47:49",
            "_id": 40,
            "id": "facebook|680594762097202",
            "flag.FlagType": 2,
            "flag.Text": ""
          }
        ]
      }
    ]
  }
}
```

Notice how FlagType 6 and 3 disappear.

Am I doing something wrong here?

### PR DESCRIPTION
**Pull request by AngeloBusato**
Fixes #810

apoc.convert.toTree returns invalid data?

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Fix bug when export data from apoc.convert.toTree

### CODE REVIEW

File: src/main/java/apoc/convert/Json.java [hunk 1]
```diff
@@ -82,20 +79,35 @@ public Object getJsonProperty(@Name("node") Node node, @Name("key") String key,@
...
                     // todo take direction into account and create collection into outgoing direction ??
                     // parent-[:HAS_CHILD]->(child) vs. (parent)<-[:PARENT_OF]-(child)
                     if (!nMap.containsKey(typeName)) nMap.put(typeName, new ArrayList<>(16));
-                    List list = (List) nMap.get(typeName);
-                    if (!list.contains(mMap))
-                        list.add(mMap); // todo performance, use set instead and convert to map at the end?
+                    List<Map<String, Object>> list = (List) nMap.get(typeName);
+                    Map<String, Object> mMap = null;
+                    int indexOf = -1;
+                    for (int i = 0, length = list.size(); i < length;i++) { // we try to retrieve the element from the list
```
Comment (jexp) [inline src/main/java/apoc/convert/Json.java]: list.stream.find()

File: src/main/java/apoc/convert/Json.java [hunk 2]
```diff
@@ -82,20 +79,35 @@ public Object getJsonProperty(@Name("node") Node node, @Name("key") String key,@
...
+                            indexOf = i;
+                            break;
+                        }
+                    }
+                    if (mMap == null) {
+                        mMap = toMap(m);
+                    }
+                    mMap = addRelProperties(mMap, typeName, r);
+                    if (indexOf != -1) { // if the element is already present we updated it
+                        list.set(indexOf, mMap);
```
Comment (jexp) [inline src/main/java/apoc/convert/Json.java]: is not necessary

File: src/main/java/apoc/convert/Json.java [hunk 3]
```diff
@@ -82,20 +79,35 @@ public Object getJsonProperty(@Name("node") Node node, @Name("key") String key,@
...
-                    Map<String, Object> mMap = maps.computeIfAbsent(m.getId(), (id) -> toMap(m));
-                    String typeName = r.getType().name();
-                    if (lowerCaseRels) typeName = typeName.toLowerCase();
-                    mMap = addRelProperties(mMap, typeName, r);
+                    String typeName = lowerCaseRels ? r.getType().name().toLowerCase() : r.getType().name();
                     // todo take direction into account and create collection into outgoing direction ??
                     // parent-[:HAS_CHILD]->(child) vs. (parent)<-[:PARENT_OF]-(child)
                     if (!nMap.containsKey(typeName)) nMap.put(typeName, new ArrayList<>(16));
-                    List list = (List) nMap.get(typeName);
-                    if (!list.contains(mMap))
```
Comment (jexp) [inline src/main/java/apoc/convert/Json.java]: this is the only bit that has to be changed imho. the other changes are not relevant.
Also if the map is already in the `maps` datastructure doesn't it also imply that it's already in list.
