### PR TITLE
Fixes #1498 

### LINKED ISSUE #1498: apoc.custom.asProcedure doesn't work when returning Node, Path, Relationship
When I use the example of the [documentation ](https://neo4j.com/docs/labs/apoc/4.0/cypher-execution/cypher-based-procedures-functions/):

```
CALL apoc.custom.asProcedure('neighbours',
  'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour','read',
  [['neighbour','NODE']],[['name','STRING']], 'get neighbours of a person');

CALL custom.neighbours('Keanu Reeves') YIELD neighbour;
```

The result is 
```
Neo.DatabaseError.General.UnknownError
[Node[1]:org.neo4j.kernel.impl.core.NodeEntity] is not a supported property value
```
The error is the same with Path and Relationship.

### Versions

  - OS: Windows 10
  - Neo4j: 4.0.3 (using Docker)
  - Neo4j-Apoc: 4.0.0.7

### PR DESCRIPTION
**Pull request by augonis**
Fixes #1498 

## Proposed Changes

Since `Values.of()` can't handle Nodes, Relationships and Paths, handle them separately with `ValueUtils.asAnyValue()`

### CODE REVIEW

**Comment by jexp** [comment]
Thanks a lot for your contribution. Would you mind signing our CLA: https://neo4j.com/developer/cla

File: src/main/java/apoc/custom/CypherProceduresHandler.java [hunk 1]
```diff
@@ -7,11 +7,7 @@
 import apoc.util.Util;
 import org.neo4j.collection.RawIterator;
 import org.neo4j.function.ThrowingFunction;
-import org.neo4j.graphdb.GraphDatabaseService;
-import org.neo4j.graphdb.Node;
-import org.neo4j.graphdb.QueryExecutionException;
-import org.neo4j.graphdb.Result;
-import org.neo4j.graphdb.Transaction;
+import org.neo4j.graphdb.*;
```
Comment (jexp) [inline src/main/java/apoc/custom/CypherProceduresHandler.java:10]: please try to leave imports stable :)

**Comment by augonis** [comment]
> Thanks a lot for your contribution. Would you mind signing our CLA: https://neo4j.com/developer/cla

Done!
