### PR TITLE
Fixes #2930: The apoc.import.json constraint check should works only when an unique constraint exists

### LINKED ISSUE #2930: The `apoc.import.json` constraint check should works only when an unique constraint exists
## Expected Behavior (Mandatory)

Missing constraint error

## Actual Behavior (Mandatory)

The import works

## How to Reproduce the Problem

Create a file `all.json` with label `User`:
```
{"type":"node","id":"0","labels":["User"],"properties":{"born":"2015-07-04T19:32:24","name":"Adam","place":{"crs":"wgs-84","latitude":33.46789,"longitude":13.1,"height":null},"male":true,"age":42,"kids":["Sam","Anna","Grace"]}}
```

Try to import the file without constraints:
```
CALL apoc.import.json('all.json')
```
this will throw an error message:
```
Missing constraint required for import. Execute this query: 
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS UNIQUE;
```

Create an existence constraint instead of an unique one.
```
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS NOT NULL
```

Retry the import and note that it's work.

### Versions

  - OS: OSX
  - Neo4j: 4.3.11
  - Neo4j-Apoc: 4.3.0.5

### PR DESCRIPTION
**Pull request by vga91**
Fixes #2930

Excluded node key and unique constraints

### CODE REVIEW

**Comment by jexp** [comment]
@ncordon do you know where we are on this?

File: core/src/main/java/apoc/export/json/JsonImporter.java [hunk 1]
```diff
@@ -174,7 +176,8 @@ private void checkConstraints(List<String> labels) {
             final String importIdName = importJsonConfig.getImportIdName();
             final String missingConstraint = labels.stream().filter(label -> 
                     StreamSupport.stream(schema.getConstraints(Label.label(label)).spliterator(), false)
-                            .noneMatch(constraint -> Iterables.contains(constraint.getPropertyKeys(), importIdName))
+                            .filter(c -> c.isConstraintType(ConstraintType.UNIQUENESS) || c.isConstraintType(ConstraintType.NODE_KEY))
```
Comment (ncordon) [inline core/src/main/java/apoc/export/json/JsonImporter.java:179]: Should this be and condition instead of or?

File: core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+import static apoc.util.BinaryTestUtil.fileToBinary;
+import static apoc.util.CompressionConfig.COMPRESSION;
+import static apoc.util.TestContainerUtil.createEnterpriseDB;
+import static apoc.util.TestContainerUtil.testCall;
+import static apoc.util.Util.map;
+import static java.lang.String.format;
+import static org.junit.Assert.assertTrue;
+import static org.junit.Assert.fail;
+
+public class ImportJsonEnterpriseTest {
```
Comment (ncordon) [inline core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java:23]: Why do we need an integration test instead of a unit test? Is it because we are touching the system database?

File: core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+    }
+
+    @AfterClass
+    public static void afterAll() {
+        session.close();
+        neo4jContainer.close();
+    }
+
+    @Test
+    public void shouldFailsWithExistenceConstraintDueToMissingUniqueConstraint() {
```
Comment (ncordon) [inline core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java:44]: Nitpick:
```suggestion
    public void shouldFailWithExistenceConstraintDueToMissingUniqueConstraint() {
```

File: core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+        } catch (RuntimeException e) {
+            assertTrue(e.getMessage().contains(MISSING_USER_CONSTRAINT));
+        } finally {
+            session.run("DROP CONSTRAINT userExistence");
+        }
+        
+    }
+
+    @Test
+    public void shouldFailsWithMultipleNodeKeyDueToMissingUniqueConstraint() {
```
Comment (ncordon) [inline core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java:63]: Nitpick:
```suggestion
    public void shouldFailWithMultipleNodeKeyDueToMissingUniqueConstraint() {
```

File: core/src/main/java/apoc/export/json/JsonImporter.java (hunk 1 above)
Comment (vga91) [reply core/src/main/java/apoc/export/json/JsonImporter.java:179]: I think it is right this way, that is, I verify that there is 
either a `CREATE CONSTRAINT name ON (n:LABEL) assert (n.ID_IMPORT) IS NODE KEY` 
or a `CREATE CONSTRAINT name ON (n:LABEL) assert n.ID_IMPORT IS UNIQUE`

File: core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java (hunk 2 above)
Comment (vga91) [reply core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java:23]: I created a new enterprise test class because I had to add `"IS NODE KEY"` constraints which are not supported in `ImportJsonTest`

**Review by ncordon — APPROVED** [review]
