### PR TITLE
Eagerly convert TxData iterables to lists

### LINKED ISSUE #1736: afterAsync Triggers produce NullPointerException
## Expected Behavior (Mandatory)
afterAsync triggers should not produce an exception when many operations are happening

## Actual Behavior (Mandatory)
afterAsync triggers can sometimes throw NullPointerException when a lot of operations are happening at once. This happens more frequently when more than one trigger exists

### Simple Dataset (where it's possibile)

```
CALL apoc.trigger.add('trig_one', 'UNWIND $createdNodes AS n SET n.trig_one = true', { phase: 'afterAsync' });
CALL apoc.trigger.add('trig_two', 'UNWIND $createdNodes AS n SET n.trig_two = true', { phase: 'afterAsync' });
// When this runs, NPE will probably come out in the logs:
UNWIND range(0, 10000) AS num CREATE (n:NodeOne { num: num });
```

### Steps (Mandatory)

  1. Run the queries
  1. Observe the logs for exceptions
  1. If none appear, try running the last query again

Example:
```
neo    | 2020-12-02 19:06:55.486+0000 WARN  [neo4j] Error executing trigger trig_one in phase afterAsync
neo    | java.lang.NullPointerException
neo    |        at org.neo4j.kernel.impl.util.collection.AbstractLinearProbeLongHashSet.valueAt(AbstractLinearProbeLongHashSet.java:314)
neo    |        at org.neo4j.kernel.impl.util.collection.AbstractLinearProbeLongHashSet$FailFastIterator.next(AbstractLinearProbeLongHashSet.java:396)
neo    |        at org.eclipse.collections.impl.lazy.primitive.CollectLongToObjectIterable$2.next(CollectLongToObjectIterable.java:82)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.asListValue(ValueUtils.java:208)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.of(ValueUtils.java:109)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.asParameterMapValue(ValueUtils.java:282)
neo    |        at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:226)
neo    |        at apoc.trigger.TriggerHandler.lambda$executeTriggers$11(TriggerHandler.java:310)
neo    |        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
neo    |        at apoc.trigger.TriggerHandler.executeTriggers(TriggerHandler.java:302)
neo    |        at apoc.trigger.TriggerHandler.lambda$afterAsync$6(TriggerHandler.java:215)
neo    |        at apoc.util.Util.retryInTx(Util.java:204)
neo    |        at apoc.util.Util.lambda$inTxFuture$4(Util.java:228)
neo    |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neo    |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
neo    |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
neo    |        at java.base/java.lang.Thread.run(Thread.java:834)
neo    | 2020-12-02 19:06:55.489+0000 WARN  [neo4j] Error executing trigger trig_two in phase afterAsync
neo    | java.lang.NullPointerException
neo    |        at org.neo4j.kernel.impl.util.collection.AbstractLinearProbeLongHashSet.valueAt(AbstractLinearProbeLongHashSet.java:314)
neo    |        at org.neo4j.kernel.impl.util.collection.AbstractLinearProbeLongHashSet$FailFastIterator.next(AbstractLinearProbeLongHashSet.java:396)
neo    |        at org.eclipse.collections.impl.lazy.primitive.CollectLongToObjectIterable$2.next(CollectLongToObjectIterable.java:82)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.asListValue(ValueUtils.java:208)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.of(ValueUtils.java:109)
neo    |        at org.neo4j.kernel.impl.util.ValueUtils.asParameterMapValue(ValueUtils.java:282)
neo    |        at org.neo4j.kernel.impl.coreapi.TransactionImpl.execute(TransactionImpl.java:226)
neo    |        at apoc.trigger.TriggerHandler.lambda$executeTriggers$11(TriggerHandler.java:310)
neo    |        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
neo    |        at apoc.trigger.TriggerHandler.executeTriggers(TriggerHandler.java:302)
neo    |        at apoc.trigger.TriggerHandler.lambda$afterAsync$6(TriggerHandler.java:215)
neo    |        at apoc.util.Util.retryInTx(Util.java:204)
neo    |        at apoc.util.Util.lambda$inTxFuture$4(Util.java:228)
neo    |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
neo    |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
neo    |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
neo    |        at java.base/java.lang.Thread.run(Thread.java:834)

```
## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOS 10.15.7
  - Neo4j: 4.1.3-enterprise
  - Neo4j-Apoc: 4.1.0.4-all

### PR DESCRIPTION
**Pull request by ivangreene**
Fixes #1736 

These are ultimately converted to a Collection
when the Cypher query is executed anyway, so no
real performance advantage to the old way

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Eagerly convert TxData iterables to lists. This gets access to the transaction bound lazy iterables out of the way earlier, to prevent issues when the query is executed.

### CODE REVIEW

File: core/src/main/java/apoc/trigger/TriggerHandler.java [hunk 1]
```diff
@@ -287,6 +288,11 @@ public void afterRollback(TransactionData txData, Void state, GraphDatabaseServi
         );
     }
 
+    private <E> List<E> toList(Iterable<E> iterable) {
```
Comment (ivangreene) [inline core/src/main/java/apoc/trigger/TriggerHandler.java:291]: If there is a preferred method for this in one of the included libraries we can remove this method and use that

**Review by ivangreene — COMMENTED** [review]
The biggest problem here is creating a reliable test to assert that this is fixed. Let me know if anyone has ideas

**Comment by conker84** [comment]
@ivangreene thank you for the contribution, but I think that should not be done eagerly because in situations with a huge amount of entities that can cause an OOM exception because we load everything in memory, wdyt?

File: core/src/main/java/apoc/trigger/TriggerHandler.java [hunk 2]
```diff
@@ -273,10 +274,10 @@ public void afterRollback(TransactionData txData, Void state, GraphDatabaseServi
         }
         return map("transactionId", txId,
                 "commitTime", commitTime,
-                "createdNodes", txData.createdNodes(),
-                "createdRelationships", txData.createdRelationships(),
-                "deletedNodes", txData.deletedNodes(),
-                "deletedRelationships", txData.deletedRelationships(),
+                "createdNodes", toList(txData.createdNodes()),
```
Comment (conker84) [inline core/src/main/java/apoc/trigger/TriggerHandler.java:277]:
```suggestion
                "createdNodes", Convert.convertToList(txData.createdNodes()),
```

File: core/src/main/java/apoc/trigger/TriggerHandler.java [hunk 3]
```diff
@@ -273,10 +274,10 @@ public void afterRollback(TransactionData txData, Void state, GraphDatabaseServi
...
+                "createdRelationships", toList(txData.createdRelationships()),
+                "deletedNodes", toList(txData.deletedNodes()),
```
Comment (conker84) [inline core/src/main/java/apoc/trigger/TriggerHandler.java:279]:
```suggestion
                "deletedNodes", Convert.convertToList(txData.deletedNodes()),
```

File: core/src/main/java/apoc/trigger/TriggerHandler.java [hunk 4]
```diff
@@ -273,10 +274,10 @@ public void afterRollback(TransactionData txData, Void state, GraphDatabaseServi
...
+                "deletedRelationships", toList(txData.deletedRelationships()),
```
Comment (conker84) [inline core/src/main/java/apoc/trigger/TriggerHandler.java:280]:
```suggestion
                "deletedRelationships", Convert.convertToList(txData.deletedRelationships()),
```

**Review by conker84 — APPROVED** [review]
@ivangreene I just had a chat with @jexp and looking at the stack trace the conversion to list seems also to happen internally so we can do this because it will happen anyway. Please remove the `toList` method and used the one that I suggested.
Thank you so much

**Comment by ivangreene** [comment]
@conker84 thanks for reviewing, just made the requested change

**Review by conker84 — APPROVED** [review]
LGTM
